import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Metadata, Signature } from "@tufjs/models";
import { afterEach, describe, expect, it } from "vitest";
import { writeManifest } from "../../scripts/release-manifest.mjs";
import { main as keygen } from "../../scripts/tuf-keygen.mjs";
import { ReleaseToolError, assertOutsideRepo, initRoot, loadSigner, publicHexFromJwk, refreshTimestamp, release, signerFromPem } from "../../scripts/tuf-lib.mjs";
import { main as tool } from "../../scripts/tuf-release.mjs";
import { TufClient, type TufOutcome } from "../../src/update/tuf.js";
import type { TufBuildConfig } from "../../src/update/buildConfig.js";
import { startTufServer, type TufServer } from "../fixtures/tufServer.js";

/**
 * The release signing tools (D#6 R6-3) against the runner's REAL TUF client (R6-2a: tuf-js over real TLS to a local server). Nothing
 * here is hand-written metadata: every document the client verifies was produced by `scripts/tuf-release.mjs`, with throwaway keys
 * generated by `scripts/tuf-keygen.mjs` into a temporary directory outside the repository.
 */

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SCRIPTS = path.join(HERE, "..", "..", "scripts");
const DAY = 86_400_000;
const T1 = "v1.0.0/fx-runner-linux-x64";
const T2 = "v1.1.0/fx-runner-linux-x64";
const bytesOf = (version: string): Buffer => Buffer.from(`fx-runner ${version}\n`.repeat(50));

const cleanups: Array<() => Promise<void> | void> = [];
afterEach(async () => {
  for (const fn of cleanups.splice(0)) await fn();
});

interface Keys {
  root: string;
  root2: string;
  targets: string;
  targets2: string;
  online: string;
  online2: string;
  pub: Record<"root" | "root2" | "targets" | "targets2" | "online" | "online2", string>;
}

interface Run {
  code: number;
  out: string;
  err: string;
}

interface World {
  work: string;
  meta: string;
  /** A pristine copy of 1.root.json, made at init-root: the file the owner holds and passes as --trusted-root. */
  trusted: string;
  keys: Keys;
  /** Run the release tool in-process. */
  run(argv: string[], over?: { now?: Date; environment?: NodeJS.ProcessEnv }): Run;
  /** Publish a release of `version` to the metadata directory (artifacts are written, hashed by release-manifest.mjs). */
  publish(version: string, over?: { now?: Date }): void;
  server: TufServer;
  /** Copy the metadata directory to the server. */
  sync(): void;
  client(stateDir?: string): TufClient;
  stateDir: string;
}

async function world(): Promise<World> {
  const work = mkdtempSync(path.join(tmpdir(), "fx-r63-"));
  const keyDir = path.join(work, "keys");
  const names = ["root", "root2", "targets", "targets2", "online", "online2"] as const;
  const keys = { pub: {} } as Keys;
  for (const name of names) {
    const file = path.join(keyDir, `${name}.pem`);
    let out = "";
    expect(keygen(["--out", file], { out: (s: string) => (out += s), err: () => undefined })).toBe(0);
    const pubFile = path.join(work, `${name}.pub.json`);
    writeFileSync(pubFile, out);
    keys[name] = file;
    keys.pub[name] = pubFile;
  }
  const meta = path.join(work, "meta");
  const trusted = path.join(work, "trusted-1.root.json");
  const server = await startTufServer({ rootText: "", metadata: new Map(), files: new Map(), keys: undefined as never });
  const stateDir = mkdtempSync(path.join(tmpdir(), "fx-r63-state-"));
  cleanups.push(async () => {
    await server.close();
    rmSync(work, { recursive: true, force: true });
    rmSync(stateDir, { recursive: true, force: true });
  });
  const world: World = {
    work,
    meta,
    trusted,
    keys,
    server,
    stateDir,
    run(argv, over = {}) {
      let out = "";
      let err = "";
      // The four commands that build on existing metadata need the trusted root; tests that attack it pass their own.
      if (["release", "refresh-timestamp", "rotate-root", "check"].includes(argv[0] ?? "") && !argv.includes("--trusted-root") && existsSync(trusted)) argv = [...argv, "--trusted-root", trusted];
      const code = tool(argv, { now: over.now ?? new Date(), environment: over.environment ?? {}, out: (s: string) => (out += s), err: (s: string) => (err += s) });
      return { code, out, err };
    },
    publish(version, over = {}) {
      const artifacts = path.join(work, `artifacts-${version}`);
      mkdirSync(artifacts, { recursive: true });
      writeFileSync(path.join(artifacts, "fx-runner-linux-x64"), bytesOf(version));
      server.files.set(`v${version}/fx-runner-linux-x64`, bytesOf(version));
      const { file } = writeManifest(artifacts, version);
      const result = world.run(["release", "--dir", meta, "--manifest", file, "--targets-key", keys.targets, "--online-key", keys.online], over);
      expect(result.err).toBe("");
      expect(result.code).toBe(0);
    },
    sync() {
      server.metadata.clear();
      for (const name of readdirSync(meta)) if (name.endsWith(".json")) server.metadata.set(name, readFileSync(path.join(meta, name)));
    },
    client(state = stateDir) {
      const root = readFileSync(path.join(meta, "1.root.json"), "utf8");
      const build: TufBuildConfig = { root, metadataBaseUrl: server.metadataBase, targetBaseUrl: server.targetBase };
      return new TufClient({ stateDir: state, build, ca: server.ca });
    },
  };
  return world;
}

async function initialised(over: { now?: Date } = {}): Promise<World> {
  const w = await world();
  const r = w.run(["init-root", "--dir", w.meta, "--root-key", w.keys.root, "--targets-pubkey", w.keys.pub.targets, "--online-pubkey", w.keys.pub.online], over);
  expect(r.err).toBe("");
  expect(r.code).toBe(0);
  copyFileSync(path.join(w.meta, "1.root.json"), w.trusted);
  return w;
}

const sha = (data: Buffer): string => createHash("sha256").update(data).digest("hex");

function expectVerified(outcome: TufOutcome, version: string): void {
  expect(outcome.ok).toBe(true);
  if (!outcome.ok) return;
  expect(outcome.sha256).toBe(sha(bytesOf(version)));
  expect(readFileSync(outcome.file).equals(bytesOf(version))).toBe(true);
}

const refusedWith = (outcome: TufOutcome, code: string): void => {
  expect(outcome.ok).toBe(false);
  if (outcome.ok) return;
  expect(outcome.state === "paused" ? outcome.code : outcome.state === "refused" ? outcome.code : outcome.state).toBe(code);
};

const cachedRoot = (w: World, state = w.stateDir): number => (JSON.parse(readFileSync(path.join(state, "tuf", "root.json"), "utf8")) as { signed: { version: number } }).signed.version;

/** Damage a file's signatures after signing: keep the first `keep` and drop the rest. The signed part is untouched. */
function keepSignatures(file: string, keep: (keyId: string) => boolean): void {
  const json = JSON.parse(readFileSync(file, "utf8")) as { signatures: Array<{ keyid: string }> };
  json.signatures = json.signatures.filter((s) => keep(s.keyid));
  writeFileSync(file, JSON.stringify(json));
}

describe("acceptance 1: the round trip through the real client", () => {
  it("init-root, release, then refresh-timestamp, then rotate-root, each verified by tuf-js", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    w.sync();
    const client = w.client();
    expectVerified(await client.fetchTarget(T1), "1.0.0");
    const firstTimestamp = JSON.parse(readFileSync(path.join(w.meta, "timestamp.json"), "utf8")).signed.version as number;

    // A weekly re-sign (a second later by the clock the tool is told): a new timestamp (and snapshot) that still verifies.
    const refreshed = w.run(["refresh-timestamp", "--dir", w.meta, "--online-key", w.keys.online], { now: new Date(Date.now() + 1000) });
    expect(refreshed.err).toBe("");
    expect(refreshed.code).toBe(0);
    expect(JSON.parse(readFileSync(path.join(w.meta, "timestamp.json"), "utf8")).signed.version).toBe(firstTimestamp + 1);
    expect(existsSync(path.join(w.meta, "2.snapshot.json"))).toBe(true);
    w.sync();
    expectVerified(await client.fetchTarget(T1), "1.0.0");

    // Root rotation to a new root key: a client that trusts root 1 accepts root 2, and so does one that has never run.
    const rotated = w.run(["rotate-root", "--dir", w.meta, "--root-key", w.keys.root, "--new-root-key", w.keys.root2]);
    expect(rotated.err).toBe("");
    expect(rotated.code).toBe(0);
    expect(rotated.out).not.toContain("run release --renew");
    w.sync();
    expectVerified(await client.fetchTarget(T1), "1.0.0");
    expect(cachedRoot(w)).toBe(2);
    const fresh = mkdtempSync(path.join(tmpdir(), "fx-r63-fresh-"));
    cleanups.push(() => rmSync(fresh, { recursive: true, force: true }));
    expectVerified(await w.client(fresh).fetchTarget(T1), "1.0.0");
    expect(cachedRoot(w, fresh)).toBe(2);
    expect(w.run(["check", "--dir", w.meta]).out).toContain("ok: root 2");
  });

  it("rotating the targets and online keys needs a renew with the new keys, and a client refuses until then", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    const rotated = w.run(["rotate-root", "--dir", w.meta, "--root-key", w.keys.root, "--targets-pubkey", w.keys.pub.targets2, "--online-pubkey", w.keys.pub.online2]);
    expect(rotated.code).toBe(0);
    expect(rotated.out).toContain("run release --renew");
    w.sync();
    refusedWith(await w.client().fetchTarget(T1), "bad_signature");
    // The old keys can no longer sign: the tool refuses them before writing anything.
    const before = readdirSync(w.meta).sort();
    const stale = w.run(["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.targets, "--online-key", w.keys.online]);
    expect(stale.code).toBe(1);
    expect(stale.err).toContain("not one of the targets keys");
    expect(readdirSync(w.meta).sort()).toEqual(before);
    const refused = w.run(["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.targets2, "--online-key", w.keys.online2]);
    expect(refused.code).toBe(1);
    expect(refused.err).toContain("give --artifacts");
    const renewed = w.run(["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.targets2, "--online-key", w.keys.online2, "--artifacts", genuineArtifacts(w, ["1.0.0"])]);
    expect(renewed.err).toBe("");
    expect(renewed.code).toBe(0);
    // The carried list was vouched for by root 1, not the newest root: the tool says so.
    expect(renewed.out).toContain("verified under root 1");
    w.sync();
    expectVerified(await w.client().fetchTarget(T1), "1.0.0");
  });

  it("a new targets version drops a bad release; the older one stays withdrawn and the newer one verifies", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    w.publish("1.1.0");
    w.sync();
    expectVerified(await w.client().fetchTarget(T1), "1.0.0");
    const drop = w.run(["release", "--dir", w.meta, "--drop", "1.0.0", "--targets-key", w.keys.targets, "--online-key", w.keys.online]);
    expect(drop.err).toBe("");
    expect(drop.code).toBe(0);
    expect(drop.out).toContain(T2);
    expect(drop.out).not.toContain(T1);
    w.sync();
    const client = w.client();
    refusedWith(await client.fetchTarget(T1), "target_not_found");
    expectVerified(await client.fetchTarget(T2), "1.1.0");
    // Dropping what is not listed is a mistake, not a no-op.
    expect(w.run(["release", "--dir", w.meta, "--drop", "9.9.9", "--targets-key", w.keys.targets, "--online-key", w.keys.online]).code).toBe(1);
  });

  it("a released file is never replaced by different bytes", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    const artifacts = path.join(w.work, "artifacts-1.0.0");
    writeFileSync(path.join(artifacts, "fx-runner-linux-x64"), "different bytes");
    const { file } = writeManifest(artifacts, "1.0.0");
    const r = w.run(["release", "--dir", w.meta, "--manifest", file, "--targets-key", w.keys.targets, "--online-key", w.keys.online]);
    expect(r.code).toBe(1);
    expect(r.err).toContain("already released with different contents");
  });
});

describe("acceptance 2 and 3 (tool side): keys stay out of the repo and off the screen, expiry defaults", () => {
  it("refuses a private key path inside this repository, inside any git working tree, and over an existing file", async () => {
    const inRepo = path.join(SCRIPTS, "..", "..", "..", "should-not-exist.pem");
    let out = "";
    let err = "";
    expect(keygen(["--out", inRepo], { out: (s: string) => (out += s), err: (s: string) => (err += s) })).toBe(1);
    expect(existsSync(inRepo)).toBe(false);
    expect(err).toContain("inside this repository");
    expect(out).toBe("");

    const tree = mkdtempSync(path.join(tmpdir(), "fx-r63-tree-"));
    cleanups.push(() => rmSync(tree, { recursive: true, force: true }));
    execFileSync("git", ["init", "-q", tree]);
    expect(() => assertOutsideRepo(path.join(tree, "deeper", "k.pem"))).toThrow(ReleaseToolError);

    const w = await world();
    expect(keygen(["--out", w.keys.root], { out: () => undefined, err: (s: string) => (err += s) })).toBe(1);
    expect(err).toContain("already exists");
  });

  it("prints only the public JWK, writes the private half 0600, and never shows key material", async () => {
    const dir = mkdtempSync(path.join(tmpdir(), "fx-r63-kg-"));
    cleanups.push(() => rmSync(dir, { recursive: true, force: true }));
    const file = path.join(dir, "sub", "k.pem");
    const spawned = execFileSync(process.execPath, [path.join(SCRIPTS, "tuf-keygen.mjs"), "--out", file], { encoding: "utf8" });
    const pem = readFileSync(file, "utf8");
    expect(statSync(file).mode & 0o777).toBe(0o600);
    expect(JSON.parse(spawned)).toEqual({ kty: "OKP", crv: "Ed25519", x: expect.stringMatching(/^[A-Za-z0-9_-]{43}$/) });
    const body = pem.replace(/-----[A-Z ]+-----|\s/g, "");
    expect(spawned).not.toContain(body);
    expect(spawned).not.toContain("PRIVATE");
    // The private scalar is the last 32 bytes of the PKCS#8 blob: it must not appear in any form on stdout.
    const scalar = Buffer.from(body, "base64").subarray(-32);
    for (const form of [scalar.toString("hex"), scalar.toString("base64"), scalar.toString("base64url")]) expect(spawned).not.toContain(form);
    expect(signerFromPem(pem).publicHex).toBe(publicHexFromJwk(JSON.parse(spawned)));
  });

  it("every release command prints no key text, even when it fails", async () => {
    const w = await initialised();
    const secret = readFileSync(w.keys.targets, "utf8").replace(/-----[A-Z ]+-----|\s/g, "");
    const outputs: string[] = [];
    outputs.push(...Object.values(w.run(["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.targets, "--online-key", w.keys.online])).map(String));
    outputs.push(...Object.values(w.run(["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.online, "--online-key", w.keys.online])).map(String));
    outputs.push(...Object.values(w.run(["check", "--dir", w.meta])).map(String));
    for (const text of outputs) expect(text).not.toContain(secret.slice(-30));
  });

  it("takes a key from a file path or from an environment variable NAME, and refuses key text as a value", async () => {
    const w = await initialised();
    const pem = readFileSync(w.keys.targets, "utf8");
    const onlinePem = readFileSync(w.keys.online, "utf8");
    const viaEnv = w.run(["release", "--dir", w.meta, "--renew", "--targets-key-env", "TUF_TARGETS_KEY", "--online-key-env", "TUF_ONLINE_KEY"], { environment: { TUF_TARGETS_KEY: pem, TUF_ONLINE_KEY: onlinePem } });
    expect(viaEnv.err).toBe("");
    expect(viaEnv.code).toBe(0);
    const missing = w.run(["release", "--dir", w.meta, "--renew", "--targets-key-env", "TUF_TARGETS_KEY", "--online-key-env", "TUF_ONLINE_KEY"]);
    expect(missing.code).toBe(1);
    expect(missing.err).toContain("--targets-key-env is not set");
    expect(missing.err).not.toContain("TUF_TARGETS_KEY");
    const asValue = w.run(["release", "--dir", w.meta, "--renew", "--targets-key-env", pem, "--online-key", w.keys.online]);
    expect(asValue.code).toBe(1);
    expect(asValue.err).toContain("needs a value");
    expect(asValue.err).not.toContain(pem.slice(30, 60));
    const body = pem.replace(/-----[A-Z ]+-----|\s/g, "");
    const asBody = w.run(["release", "--dir", w.meta, "--renew", "--targets-key-env", `${body}==`, "--online-key", w.keys.online]);
    expect(asBody.code).toBe(1);
    expect(asBody.err).toContain("NAME of an environment variable");
    expect(asBody.err).not.toContain(body.slice(10, 40));
    const asPath = w.run(["release", "--dir", w.meta, "--renew", "--targets-key", pem, "--online-key", w.keys.online]);
    expect(asPath.code).toBe(1);
    expect(asPath.err).toContain("needs a value");
    expect(() => loadSigner({ file: w.keys.targets, env: "X" })).toThrow(ReleaseToolError);
  });

  it("refuses a key file other users can read", async () => {
    const w = await initialised();
    execFileSync("chmod", ["644", w.keys.targets]);
    const r = w.run(["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.targets, "--online-key", w.keys.online]);
    expect(r.code).toBe(1);
    expect(r.err).toContain("readable by other users");
  });

  it("expires root 365 days, targets 90, snapshot 14, timestamp 14 by default, and each can be overridden", async () => {
    const now = new Date("2030-01-01T00:00:00.000Z");
    const w = await initialised({ now });
    w.publish("1.0.0", { now });
    const days = (name: string): number => (Date.parse(JSON.parse(readFileSync(path.join(w.meta, name), "utf8")).signed.expires) - now.getTime()) / DAY;
    expect([days("1.root.json"), days("1.targets.json"), days("1.snapshot.json"), days("timestamp.json")]).toEqual([365, 90, 14, 14]);
    const custom = w.run(["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.targets, "--online-key", w.keys.online, "--targets-days", "30", "--snapshot-days", "7", "--timestamp-days", "3"], { now });
    expect(custom.code).toBe(0);
    expect([days("2.targets.json"), days("2.snapshot.json"), days("timestamp.json")]).toEqual([30, 7, 3]);
    const root = w.run(["rotate-root", "--dir", w.meta, "--root-key", w.keys.root, "--root-days", "100"], { now });
    expect(root.code).toBe(0);
    expect(days("2.root.json")).toBe(100);
    expect(w.run(["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.targets, "--online-key", w.keys.online, "--targets-days", "0"]).code).toBe(1);
  });
});

describe("negative: the real client refuses what the tools can be made to produce badly", () => {
  it("expired metadata pauses updates; a re-sign of the online roles restores them", async () => {
    const past = new Date(Date.now() - 20 * DAY);
    const w = await initialised({ now: past });
    w.publish("1.0.0", { now: past });
    w.sync();
    const client = w.client();
    const stale = await client.fetchTarget(T1);
    expect(stale.ok).toBe(false);
    if (!stale.ok) expect(stale.state).toBe("paused");
    refusedWith(stale, "metadata_expired");

    // The weekly job's command, run now: no new release and the same targets, yet the client verifies again.
    const refreshed = w.run(["refresh-timestamp", "--dir", w.meta, "--online-key", w.keys.online]);
    expect(refreshed.err).toBe("");
    expect(refreshed.code).toBe(0);
    w.sync();
    expectVerified(await client.fetchTarget(T1), "1.0.0");
  });

  it("an expired targets file cannot be fixed by the timestamp key: the tool says so, the client pauses", async () => {
    const past = new Date(Date.now() - 100 * DAY);
    const w = await initialised({ now: past });
    w.publish("1.0.0", { now: past });
    const refresh = w.run(["refresh-timestamp", "--dir", w.meta, "--online-key", w.keys.online]);
    expect(refresh.code).toBe(1);
    expect(refresh.err).toContain("targets metadata is expired");
    // Force the online roles fresh with the library to see what a client does with expired targets.
    refreshTimestampBypassingTargetsCheck(w);
    w.sync();
    refusedWith(await w.client().fetchTarget(T1), "metadata_expired");
    // A renew with the targets key is the fix.
    expect(w.run(["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.targets, "--online-key", w.keys.online]).code).toBe(0);
    w.sync();
    expectVerified(await w.client().fetchTarget(T1), "1.0.0");
  });

  it("an expired root is refused by the tool, which sends the owner to rotate-root", async () => {
    const past = new Date(Date.now() - 400 * DAY);
    const w = await initialised({ now: past });
    const r = w.run(["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.targets, "--online-key", w.keys.online]);
    expect(r.code).toBe(1);
    expect(r.err).toContain("root metadata is expired");
  });

  it("a signature count below the threshold is refused by the tool, and by the client when a signature is removed after signing", async () => {
    const w = await world();
    const pair = (name: "targets" | "targets2") => signerFromPem(readFileSync(w.keys[name], "utf8"));
    const root = signerFromPem(readFileSync(w.keys.root, "utf8"));
    const online = signerFromPem(readFileSync(w.keys.online, "utf8"));
    initRoot({ dir: w.meta, rootSigner: root, targetsPublic: [pair("targets").publicHex, pair("targets2").publicHex], onlinePublic: online.publicHex, thresholds: { targets: 2 } });
    const trustedRoot = readFileSync(path.join(w.meta, "1.root.json"));
    const manifest = [{ version: "1.0.0", platform: "linux-x64", sha256: sha(bytesOf("1.0.0")), size: bytesOf("1.0.0").length }];
    w.server.files.set(T1, bytesOf("1.0.0"));
    expect(() => release({ dir: w.meta, trustedRoot, manifest, targetsSigners: [pair("targets")], onlineSigners: [online] })).toThrow(/threshold of the targets keys/);
    expect(existsSync(path.join(w.meta, "1.targets.json"))).toBe(false);

    release({ dir: w.meta, trustedRoot, manifest, targetsSigners: [pair("targets"), pair("targets2")], onlineSigners: [online] });
    w.sync();
    expectVerified(await w.client().fetchTarget(T1), "1.0.0");

    release({ dir: w.meta, trustedRoot, renew: true, targetsSigners: [pair("targets"), pair("targets2")], onlineSigners: [online] });
    keepSignatures(path.join(w.meta, "2.targets.json"), (id) => id === pair("targets").keyID);
    w.sync();
    const other = mkdtempSync(path.join(tmpdir(), "fx-r63-other-"));
    cleanups.push(() => rmSync(other, { recursive: true, force: true }));
    refusedWith(await w.client(other).fetchTarget(T1), "bad_signature");
  });

  it("a root rotation signed only by the new key (the old threshold unmet) is refused", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    expect(w.run(["rotate-root", "--dir", w.meta, "--root-key", w.keys.root, "--new-root-key", w.keys.root2]).code).toBe(0);
    const oldId = signerFromPem(readFileSync(w.keys.root, "utf8")).keyID;
    keepSignatures(path.join(w.meta, "2.root.json"), (id) => id !== oldId);
    w.sync();
    refusedWith(await w.client().fetchTarget(T1), "bad_signature");
  });

  it("a wrong-role key is refused by the tool before it signs, and a timestamp signed by the targets key is refused by the client", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    const before = readFileSync(path.join(w.meta, "timestamp.json"));
    const wrong = w.run(["refresh-timestamp", "--dir", w.meta, "--online-key", w.keys.targets]);
    expect(wrong.code).toBe(1);
    expect(wrong.err).toContain("not one of the snapshot keys");
    expect(readFileSync(path.join(w.meta, "timestamp.json")).equals(before)).toBe(true);
    expect(w.run(["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.online, "--online-key", w.keys.online]).err).toContain("not one of the targets keys");
    expect(w.run(["rotate-root", "--dir", w.meta, "--root-key", w.keys.targets]).err).toContain("not one of the root keys");

    // Now put a timestamp signed by the targets key where the online key's belongs.
    const file = path.join(w.meta, "timestamp.json");
    const meta = Metadata.fromJSON("timestamp" as never, JSON.parse(readFileSync(file, "utf8")));
    meta.signatures = {};
    const targetsKey = signerFromPem(readFileSync(w.keys.targets, "utf8"));
    meta.sign((data: Buffer) => new Signature({ keyID: targetsKey.keyID, sig: targetsKey.sign(data) }));
    writeFileSync(file, JSON.stringify(meta.toJSON()));
    w.sync();
    refusedWith(await w.client().fetchTarget(T1), "bad_signature");
  });

  it("refuses to run init-root twice, and a root key that is also a targets or online key", async () => {
    const w = await initialised();
    expect(w.run(["init-root", "--dir", w.meta, "--root-key", w.keys.root, "--targets-pubkey", w.keys.pub.targets, "--online-pubkey", w.keys.pub.online]).code).toBe(1);
    const other = path.join(w.work, "meta2");
    const same = w.run(["init-root", "--dir", other, "--root-key", w.keys.root, "--targets-pubkey", w.keys.pub.root, "--online-pubkey", w.keys.pub.online]);
    expect(same.code).toBe(1);
    expect(same.err).toContain("different key");
    expect(existsSync(other)).toBe(false);
  });

  it("an unknown flag or command is a usage error, and a public key file with a private field is refused", async () => {
    const w = await initialised();
    expect(w.run(["nope"]).code).toBe(2);
    expect(w.run(["check", "--dir", w.meta, "--force"]).code).toBe(1);
    const bad = path.join(w.work, "bad.pub.json");
    writeFileSync(bad, JSON.stringify({ ...JSON.parse(readFileSync(w.keys.pub.targets, "utf8")), d: "AAAA" }));
    const r = w.run(["init-root", "--dir", path.join(w.work, "m3"), "--root-key", w.keys.root, "--targets-pubkey", bad, "--online-pubkey", w.keys.pub.online]);
    expect(r.code).toBe(1);
    expect(r.err).toContain("not public");
  });
});

/**
 * Re-sign the online roles with fresh expiry even though the targets are about to expire (what the tool refuses once they have): the
 * clock is set to 50 days after signing, when the targets are still valid, with long online lifetimes. Every signature stays genuine.
 */
function refreshTimestampBypassingTargetsCheck(w: World): void {
  const later = new Date(Date.now() - 100 * DAY + 50 * DAY);
  refreshTimestamp({ dir: w.meta, trustedRoot: readFileSync(w.trusted), onlineSigners: [signerFromPem(readFileSync(w.keys.online, "utf8"))], days: { snapshot: 90, timestamp: 90 }, now: later });
}

// ---------------------------------------------------------------------------------------------------- fix round 1: verify the input

const readJson = (file: string): ReturnType<typeof JSON.parse> => JSON.parse(readFileSync(file, "utf8"));
const noStrayFiles = (w: World, names: string[]): void => {
  for (const name of names) expect(existsSync(path.join(w.meta, name)), name).toBe(false);
};

describe("the tools verify everything they build on against a trusted root before signing", () => {
  it("an unsigned v9.9.9 entry added to the previous targets file is refused by release and by refresh-timestamp, and is never re-signed", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    const file = path.join(w.meta, "1.targets.json");
    const json = readJson(file);
    json.signed.targets["v9.9.9/fx-runner-linux-x64"] = { length: 5, hashes: { sha256: "ab".repeat(32) } };
    writeFileSync(file, JSON.stringify(json));
    const before = readdirSync(w.meta).sort();
    const next = path.join(w.work, "artifacts-1.1.0");
    mkdirSync(next, { recursive: true });
    writeFileSync(path.join(next, "fx-runner-linux-x64"), bytesOf("1.1.0"));
    const { file: manifest } = writeManifest(next, "1.1.0");
    const r = w.run(["release", "--dir", w.meta, "--manifest", manifest, "--targets-key", w.keys.targets, "--online-key", w.keys.online]);
    expect(r.code).toBe(1);
    expect(r.err).toContain("threshold of the targets keys");
    expect(readdirSync(w.meta).sort()).toEqual(before);
    const refresh = w.run(["refresh-timestamp", "--dir", w.meta, "--online-key", w.keys.online]);
    expect(refresh.code).toBe(1);
    expect(refresh.err).toContain("threshold of the targets keys");
    expect(readdirSync(w.meta).sort()).toEqual(before);
    expect(w.run(["check", "--dir", w.meta]).code).toBe(1);
  });

  it("a changed hash on a released entry is not accepted as the baseline for the same-bytes guard", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    const file = path.join(w.meta, "1.targets.json");
    const json = readJson(file);
    json.signed.targets[T1].hashes.sha256 = sha(Buffer.from("different bytes"));
    writeFileSync(file, JSON.stringify(json));
    const artifacts = path.join(w.work, "artifacts-1.0.0");
    writeFileSync(path.join(artifacts, "fx-runner-linux-x64"), "different bytes");
    const { file: manifest } = writeManifest(artifacts, "1.0.0");
    const r = w.run(["release", "--dir", w.meta, "--manifest", manifest, "--targets-key", w.keys.targets, "--online-key", w.keys.online]);
    expect(r.code).toBe(1);
    expect(r.err).toContain("threshold of the targets keys");
    noStrayFiles(w, ["2.targets.json"]);
  });

  it("a newer targets file that the snapshot does not point to is refused", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    copyFileSync(path.join(w.meta, "1.targets.json"), path.join(w.meta, "2.targets.json"));
    for (const argv of [["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.targets, "--online-key", w.keys.online], ["refresh-timestamp", "--dir", w.meta, "--online-key", w.keys.online], ["check", "--dir", w.meta]]) {
      const r = w.run(argv);
      expect(r.code, argv[0]).toBe(1);
      expect(r.err, argv[0]).toContain("snapshot points to");
    }
  });

  it("a timestamp signed by the wrong role's key is refused by the tools before they build on it", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    const file = path.join(w.meta, "timestamp.json");
    const meta = Metadata.fromJSON("timestamp" as never, readJson(file));
    meta.signatures = {};
    const wrong = signerFromPem(readFileSync(w.keys.targets, "utf8"));
    meta.sign((data: Buffer) => new Signature({ keyID: wrong.keyID, sig: wrong.sign(data) }));
    writeFileSync(file, JSON.stringify(meta.toJSON()));
    for (const argv of [["refresh-timestamp", "--dir", w.meta, "--online-key", w.keys.online], ["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.targets, "--online-key", w.keys.online], ["check", "--dir", w.meta]]) {
      const r = w.run(argv);
      expect(r.code, argv[0]).toBe(1);
      expect(r.err, argv[0]).toContain("timestamp.json is not signed by a threshold");
    }
  });

  /** 1.root.json altered to name an attacker's targets key. The trusted copy is untouched. */
  function tamperRoot1(w: World): void {
    const file = path.join(w.meta, "1.root.json");
    const json = readJson(file);
    const attacker = signerFromPem(readFileSync(w.keys.targets2, "utf8"));
    const targetsId = json.signed.roles.targets.keyids[0] as string;
    json.signed.keys[targetsId].keyval.public = attacker.publicHex;
    writeFileSync(file, JSON.stringify(json));
  }

  it("a tampered 1.root.json naming an attacker's key is refused by rotate-root, release, refresh-timestamp and check against the trusted root", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    tamperRoot1(w);
    const before = readdirSync(w.meta).sort();
    const attempts: Array<[string, string[]]> = [
      ["rotate-root", ["rotate-root", "--dir", w.meta, "--root-key", w.keys.root, "--new-root-key", w.keys.root2]],
      ["release", ["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.targets, "--online-key", w.keys.online]],
      ["refresh-timestamp", ["refresh-timestamp", "--dir", w.meta, "--online-key", w.keys.online]],
      ["check", ["check", "--dir", w.meta]],
    ];
    for (const [name, argv] of attempts) {
      const r = w.run(argv);
      expect(r.code, name).toBe(1);
      expect(r.err, name).toContain("not the trusted root");
      expect(r.out, name).toBe("");
    }
    expect(readdirSync(w.meta).sort()).toEqual(before);
  });

  it("every command refuses to run without a trusted root, and without a readable one", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    const none = path.join(w.work, "nothing.json");
    const commands = [
      ["rotate-root", "--root-key", w.keys.root, "--new-root-key", w.keys.root2],
      ["release", "--renew", "--targets-key", w.keys.targets, "--online-key", w.keys.online],
      ["refresh-timestamp", "--online-key", w.keys.online],
      ["check"],
    ];
    for (const rest of commands) {
      const argv = [rest[0] as string, "--dir", w.meta, ...rest.slice(1)];
      let bareErr = "";
      expect(tool(argv, { environment: {}, out: () => undefined, err: (e: string) => (bareErr += e) }), rest[0]).toBe(1);
      expect(bareErr, rest[0]).toContain("--trusted-root is required");
      let err = "";
      expect(tool([...argv, "--trusted-root", none], { environment: {}, out: () => undefined, err: (e: string) => (err += e) }), rest[0]).toBe(1);
      expect(err, rest[0]).toContain("the file given for --trusted-root could not be read");
      expect(err, rest[0]).not.toContain(none);
    }
  });

  it("a root chain link that is not signed by the previous root is refused, even when the newest root signs itself", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    expect(w.run(["rotate-root", "--dir", w.meta, "--root-key", w.keys.root, "--new-root-key", w.keys.root2]).code).toBe(0);
    const oldId = signerFromPem(readFileSync(w.keys.root, "utf8")).keyID;
    keepSignatures(path.join(w.meta, "2.root.json"), (id) => id !== oldId);
    for (const argv of [["check", "--dir", w.meta], ["rotate-root", "--dir", w.meta, "--root-key", w.keys.root2, "--new-root-key", w.keys.root]]) {
      const r = w.run(argv);
      expect(r.code, argv[0]).toBe(1);
      expect(r.err, argv[0]).toContain("2.root.json (against root 1)");
    }
  });

  it("check verifies artifact hashes when the artifacts are present, and says what it did not check", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    const artifacts = path.join(w.work, "check-artifacts");
    mkdirSync(path.join(artifacts, "v1.0.0"), { recursive: true });
    const none = w.run(["check", "--dir", w.meta, "--artifacts", artifacts]);
    expect(none.code).toBe(0);
    expect(none.out).toContain("not found (not checked): v1.0.0/fx-runner-linux-x64");
    expect(w.run(["check", "--dir", w.meta]).out).toContain("artifacts: not checked");
    writeFileSync(path.join(artifacts, T1), bytesOf("1.0.0"));
    const good = w.run(["check", "--dir", w.meta, "--artifacts", artifacts]);
    expect(good.code).toBe(0);
    expect(good.out).toContain("artifacts checked: 1, not found (not checked): none");
    writeFileSync(path.join(artifacts, T1), bytesOf("1.0.1"));
    const bad = w.run(["check", "--dir", w.meta, "--artifacts", artifacts]);
    expect(bad.code).toBe(1);
    expect(bad.err).toContain("does not match the length and SHA-256");
  });
});

describe("role keys are distinct", () => {
  it("init-root refuses any key shared between root, targets and online", async () => {
    const w = await world();
    const base = ["init-root", "--dir", w.meta];
    const cases: Array<[string, string[]]> = [
      ["targets == online", [...base, "--root-key", w.keys.root, "--targets-pubkey", w.keys.pub.targets, "--online-pubkey", w.keys.pub.targets]],
      ["root == targets", [...base, "--root-key", w.keys.root, "--targets-pubkey", w.keys.pub.root, "--online-pubkey", w.keys.pub.online]],
      ["root == online", [...base, "--root-key", w.keys.root, "--targets-pubkey", w.keys.pub.targets, "--online-pubkey", w.keys.pub.root]],
    ];
    for (const [name, argv] of cases) {
      const r = w.run(argv);
      expect(r.code, name).toBe(1);
      expect(r.err, name).toContain("must be different keys");
    }
    expect(existsSync(w.meta)).toBe(false);
  });

  it("rotate-root refuses a rotation that makes any two roles share a key", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    const cases: Array<[string, string[]]> = [
      ["new targets == online", ["--targets-pubkey", w.keys.pub.online]],
      ["new online == targets", ["--online-pubkey", w.keys.pub.targets]],
      ["new online == root", ["--online-pubkey", w.keys.pub.root]],
      ["new root key == targets key", ["--new-root-key", w.keys.targets]],
    ];
    for (const [name, rest] of cases) {
      const r = w.run(["rotate-root", "--dir", w.meta, "--root-key", w.keys.root, ...rest]);
      expect(r.code, name).toBe(1);
      expect(r.err, name).toContain("must be different keys");
    }
    noStrayFiles(w, ["2.root.json"]);
  });
});

describe("error text never echoes argv or environment values", () => {
  it("an unknown argument, an unset variable, an unreadable file or directory print fixed text or the flag name only", async () => {
    const w = await initialised();
    const body = readFileSync(w.keys.targets, "utf8").replace(/-----[A-Z ]+-----|\s/g, "");
    const marker = "ZZmarker9";
    const seed = `a${createHash("sha256").update("seed").digest("hex").slice(0, 40)}`;
    const attempts: Array<[string, string[], string]> = [
      ["positional PEM body", ["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.targets, "--online-key", w.keys.online, body], body.slice(8, 40)],
      ["positional marker", ["check", "--dir", w.meta, marker], marker],
      ["hex seed as env NAME, unset", ["release", "--dir", w.meta, "--renew", "--targets-key-env", seed, "--online-key", w.keys.online], seed],
      ["key path that does not exist", ["release", "--dir", w.meta, "--renew", "--targets-key", `/nonexistent/${marker}`, "--online-key", w.keys.online], marker],
      ["pubkey path that does not exist", ["rotate-root", "--dir", w.meta, "--root-key", w.keys.root, "--targets-pubkey", `/nonexistent/${marker}`], marker],
      ["metadata directory that does not exist", ["check", "--dir", `/nonexistent/${marker}`], marker],
      ["trusted root that does not exist", ["check", "--dir", w.meta, "--trusted-root", `/nonexistent/${marker}`], marker],
    ];
    for (const [name, argv, secret] of attempts) {
      const r = w.run(argv);
      expect(r.code, name).toBe(1);
      expect(r.err, name).not.toContain(secret);
      expect(r.out, name).not.toContain(secret);
    }
    // The ones that read a file name the flag, so the owner can find the mistake.
    expect(w.run(["release", "--dir", w.meta, "--renew", "--targets-key", `/nonexistent/${marker}`, "--online-key", w.keys.online]).err).toContain("--targets-key could not be read");
    expect(w.run(["rotate-root", "--dir", w.meta, "--root-key", w.keys.root, "--targets-pubkey", `/nonexistent/${marker}`]).err).toContain("--targets-pubkey could not be read");
    expect(w.run(["release", "--dir", w.meta, "--renew", "--targets-key-env", seed, "--online-key", w.keys.online]).err).toContain("--targets-key-env is not set");
    // "exactly one of" names the flag.
    expect(w.run(["release", "--dir", w.meta, "--renew", "--online-key", w.keys.online]).err).toContain("exactly one of --targets-key");
  });

  it("a key pasted as an environment value that fails to parse is not echoed either", async () => {
    const w = await initialised();
    const pem = readFileSync(w.keys.targets, "utf8");
    const mangled = pem.replace("PRIVATE", "PRIV8TE");
    const r = w.run(["release", "--dir", w.meta, "--renew", "--targets-key-env", "TK", "--online-key", w.keys.online], { environment: { TK: mangled } });
    expect(r.code).toBe(1);
    expect(r.err).not.toContain(mangled.replace(/-----[A-Z0-9 ]+-----|\s/g, "").slice(10, 40));
    expect(r.err).not.toContain("TK");
  });
});

describe("keygen refuses symbolic links in the path", () => {
  it("a link as a parent directory, as a missing-file link and as the file itself is refused, and nothing is written through it", () => {
    const base = mkdtempSync(path.join(tmpdir(), "fx-r63-link-"));
    cleanups.push(() => rmSync(base, { recursive: true, force: true }));
    const real = path.join(base, "real");
    mkdirSync(real);
    const viaLink = path.join(base, "link");
    symlinkSync(real, viaLink);
    const dangling = path.join(base, "dangling.pem");
    symlinkSync(path.join(real, "target.pem"), dangling);
    for (const out of [path.join(viaLink, "sub", "k.pem"), path.join(viaLink, "k.pem"), dangling]) {
      let err = "";
      expect(keygen(["--out", out], { out: () => undefined, err: (s: string) => (err += s) }), out).toBe(1);
      expect(err, out).toContain("symbolic link");
    }
    expect(readdirSync(real)).toEqual([]);
  });
});

/** A directory laid out as `v<x.y.z>/fx-runner-linux-x64` holding the genuine bytes of each version. */
function genuineArtifacts(w: World, versions: string[]): string {
  const dir = mkdtempSync(path.join(w.work, "carried-"));
  for (const version of versions) {
    mkdirSync(path.join(dir, `v${version}`), { recursive: true });
    writeFileSync(path.join(dir, `v${version}`, "fx-runner-linux-x64"), bytesOf(version));
  }
  return dir;
}

describe("after a key rotation, carried entries must match the real artifacts", () => {
  const FORGED = "v9.9.9/fx-runner-linux-x64";

  /** The leaked old targets key signs a release listing v9.9.9 with a hash no real file has; then the keys are rotated. */
  async function leakedThenRotated(): Promise<World> {
    const w = await initialised();
    w.publish("1.0.0");
    const manifest = path.join(w.work, "forged-manifest.json");
    writeFileSync(manifest, JSON.stringify([{ version: "9.9.9", platform: "linux-x64", sha256: "ab".repeat(32), size: 123 }]));
    const forged = w.run(["release", "--dir", w.meta, "--manifest", manifest, "--targets-key", w.keys.targets, "--online-key", w.keys.online]);
    expect(forged.code).toBe(0);
    const rotated = w.run(["rotate-root", "--dir", w.meta, "--root-key", w.keys.root, "--targets-pubkey", w.keys.pub.targets2, "--online-pubkey", w.keys.pub.online2]);
    expect(rotated.code).toBe(0);
    return w;
  }
  const renew = (w: World, extra: string[]): Run => w.run(["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.targets2, "--online-key", w.keys.online2, ...extra]);

  it("refuses an entry added under the leaked key when its artifact is absent, and when it differs, naming the entry", async () => {
    const w = await leakedThenRotated();
    const before = readdirSync(w.meta).sort();
    const absent = renew(w, ["--artifacts", genuineArtifacts(w, ["1.0.0"])]);
    expect(absent.code).toBe(1);
    expect(absent.err).toContain(FORGED);
    const differing = genuineArtifacts(w, ["1.0.0"]);
    mkdirSync(path.join(differing, "v9.9.9"), { recursive: true });
    writeFileSync(path.join(differing, FORGED), "attacker bytes");
    const mismatch = renew(w, ["--artifacts", differing]);
    expect(mismatch.code).toBe(1);
    expect(mismatch.err).toContain(`the artifact for ${FORGED} does not match`);
    expect(mismatch.err).not.toContain(differing);
    expect(readdirSync(w.meta).sort()).toEqual(before);
  });

  it("refuses a genuine entry whose artifact differs, and passes when every carried artifact is right (or the forged version is dropped)", async () => {
    const w = await leakedThenRotated();
    const tampered = genuineArtifacts(w, ["1.0.0"]);
    writeFileSync(path.join(tampered, "v1.0.0", "fx-runner-linux-x64"), "not the release");
    const bad = renew(w, ["--drop", "9.9.9", "--artifacts", tampered]);
    expect(bad.code).toBe(1);
    expect(bad.err).toContain("v1.0.0/fx-runner-linux-x64 does not match");
    const good = renew(w, ["--drop", "9.9.9", "--artifacts", genuineArtifacts(w, ["1.0.0"])]);
    expect(good.err).toBe("");
    expect(good.code).toBe(0);
    expect(good.out).not.toContain(FORGED);
    expect(w.run(["check", "--dir", w.meta]).code).toBe(0);
  });

  it("a renew with no rotation needs no artifacts", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    const r = w.run(["release", "--dir", w.meta, "--renew", "--targets-key", w.keys.targets, "--online-key", w.keys.online]);
    expect(r.err).toBe("");
    expect(r.code).toBe(0);
  });
});

describe("round 2 pins", () => {
  it("a root whose own signature is missing is refused even when the previous root signed it", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    expect(w.run(["rotate-root", "--dir", w.meta, "--root-key", w.keys.root, "--new-root-key", w.keys.root2]).code).toBe(0);
    const oldId = signerFromPem(readFileSync(w.keys.root, "utf8")).keyID;
    keepSignatures(path.join(w.meta, "2.root.json"), (id) => id === oldId);
    const r = w.run(["check", "--dir", w.meta]);
    expect(r.code).toBe(1);
    expect(r.err).toContain("2.root.json (against its own keys)");
  });

  it("refresh-timestamp does not fall back to an older root after the online key was rotated", async () => {
    const w = await initialised();
    w.publish("1.0.0");
    expect(w.run(["rotate-root", "--dir", w.meta, "--root-key", w.keys.root, "--targets-pubkey", w.keys.pub.targets2, "--online-pubkey", w.keys.pub.online2]).code).toBe(0);
    const before = readdirSync(w.meta).sort();
    const r = w.run(["refresh-timestamp", "--dir", w.meta, "--online-key", w.keys.online2]);
    expect(r.code).toBe(1);
    expect(r.err).toContain("is not signed by a threshold");
    expect(readdirSync(w.meta).sort()).toEqual(before);
  });

  it("a missing or unreadable --manifest file names the flag and not the path", async () => {
    const w = await initialised();
    const r = w.run(["release", "--dir", w.meta, "--manifest", "/nonexistent/ZZpath7", "--targets-key", w.keys.targets, "--online-key", w.keys.online]);
    expect(r.code).toBe(1);
    expect(r.err).toContain("--manifest could not be read");
    expect(r.err).not.toContain("ZZpath7");
  });
});
