import { readFileSync } from "node:fs";
import tseslint from "typescript-eslint";
import fxDom from "./apps/workspace/lint/index.mjs";
import fxCatch from "./lint/no-silent-catch.mjs";

// The silent-catch baseline (file -> number of silent catches it had when the rule landed), read as plain JSON
// so the config needs no import attribute.
const SILENT_CATCH_BASELINE = JSON.parse(readFileSync(new URL("./lint/no-silent-catch.baseline.json", import.meta.url), "utf8"));

// D#68 OPS-T1b: a logger line carries no free text. The telemetry logger takes a registered event code and
// typed fields; a string built at the call site (interpolation, concatenation, JSON.stringify) is the one way
// a payload could still ride into a line, so it is an error in every `log.`/`logger.` info|warn|error call.
// The logger's types and its runtime registry check enforce the same rule; this catches it at review time.
const LOGGER_CALL =
  "CallExpression[callee.type='MemberExpression'][callee.property.name=/^(info|warn|error)$/][callee.object.name=/^(log|logger)$/]";
const NO_BUILT_LOG_TEXT =
  "A logger call takes a registered event code and typed fields; do not build text (interpolation, concatenation, JSON.stringify). Pass an Error as `error` and register a code in packages/telemetry/src/events.ts.";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/dist/**",
      // D#37 WS-F0: the first-party e2e dist (playwright.config.ts builds it).
      "**/dist-first-party/**",
      "**/build/**",
      // D#37 WS-B: apps/workspace/build/ is hand-written source (the
      // profile-filtered build tool), not build output -- un-ignore it
      // from the generic "**/build/**" output-directory rule above.
      "!apps/workspace/build/**",
      "**/.turbo/**",
      "pnpm-lock.yaml",
      // Test fixtures represent someone else's file (a parity fixture for
      // an external site, a deliberately-malformed input, ...), not code
      // we own the style of. Linting them flags things a real fix would
      // just reintroduce next time the fixture is regenerated.
      "**/fixtures/**",
      // D#37 WS-C2 criterion 1: apps/web/public/ is a generated, gitignored
      // mirror of apps/workspace/dist/ (itself built from shell/** above),
      // written by apps/web/scripts/copy-workspace.mjs. Same reasoning as
      // the shell/** ignore just above -- not tracked in a clean checkout
      // (CI's `pnpm lint` runs before anything generates it), and not code
      // this repo owns the style of when it does exist on disk locally.
      "apps/web/public/**",
      // Auto-generated by Next.js on every build/dev/start; its triple-slash
      // references are the documented convention, not a lint violation.
      "**/next-env.d.ts",
      // D#68 OPS-T1b: deliberately rule-breaking input for the no-free-text lint test, which lints it
      // through the Node API with ignores switched off.
      "packages/telemetry/test/lint-fixtures/**",
      // Archived material (git mv'd out of the tree, e.g. key material or retired code): nothing builds,
      // tests or maintains it, so its style is not ours to lint.
      "archive/**",
    ],
  },
  // apps/workspace/shell/** is upstream code re-imported verbatim (D#37 WS-A2): a pinned jpos commit's
  // bytes, checked byte-for-byte against their source tar by import.mjs --verify. Style fixes there would
  // be overwritten on the next re-import, so the general rules skip it; only the DOM rule below runs there.
  ...tseslint.configs.recommended.map((c) => ({ ...c, ignores: [...(c.ignores ?? []), "apps/workspace/shell/**"] })),
  // The native DOM insertion methods print "null" for a null argument; see the rule's own header.
  // Covers the first-party apps and the shell sources (build output stays ignored above).
  {
    files: ["apps/workspace/apps/**/*.{js,mjs}", "apps/workspace/shell/**/*.{js,mjs}"],
    // A shell file may carry an eslint-disable for a typescript-eslint rule; the plugin must be loaded for
    // that comment to resolve (its rules stay off there).
    plugins: { "fx-dom": fxDom, "@typescript-eslint": tseslint.plugin },
    linterOptions: { reportUnusedDisableDirectives: "off" },
    rules: { "fx-dom/no-null-dom-insert": "error" },
  },
  // A server-side catch must rethrow, report, log at error/warn, or say why it swallows
  // (`// fx-swallow-ok: <reason>`). A site beyond the file's baseline count is an error; the baselined ones are
  // warnings (the burn-down list). See lint/no-silent-catch.mjs. Client code in apps/workspace is out of scope.
  {
    files: ["packages/*/src/**/*.{ts,tsx,js,mjs}", "apps/web/app/**/*.{ts,tsx}", "apps/web/lib/**/*.{ts,tsx}"],
    ignores: ["**/*.test.{ts,tsx,js,mjs}", "**/test/**", "**/fixtures/**"],
    plugins: { "fx-catch": fxCatch },
    rules: {
      "fx-catch/no-silent-catch": ["error", { baseline: SILENT_CATCH_BASELINE }],
      "fx-catch/no-silent-catch-baselined": ["warn", { baseline: SILENT_CATCH_BASELINE }],
    },
  },
  {
    files: ["**/*.{ts,tsx}"],
    ignores: ["apps/workspace/shell/**"],
    rules: {
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
    },
  },
  {
    files: ["**/*.{ts,tsx}"],
    // The telemetry package's own tests build hostile strings on purpose.
    ignores: ["packages/telemetry/test/*.ts", "apps/workspace/shell/**"],
    rules: {
      "no-restricted-syntax": [
        "error",
        { selector: `${LOGGER_CALL} TemplateLiteral[expressions.length>0]`, message: NO_BUILT_LOG_TEXT },
        { selector: `${LOGGER_CALL} BinaryExpression[operator='+'] > Literal[raw=/^["']/]`, message: NO_BUILT_LOG_TEXT },
        { selector: `${LOGGER_CALL} CallExpression[callee.object.name='JSON'][callee.property.name='stringify']`, message: NO_BUILT_LOG_TEXT },
      ],
    },
  },
);
