import { createHash, randomUUID } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import { withTenant } from "@fx/core/src/tenancy/withTenant.js";
import { emitDomainEvent } from "@fx/core/src/domain-events/emit.js";
import { redactEventPayload } from "@fx/core/src/events/redact.js";
// A relative import: @fx/features is not a dependency of this package and this
// change may not touch the lockfile.
import { resolveExposure } from "../../features/src/resolve.js";
import { FEATURE_CATALOGUE } from "../../features/src/featureExposure.js";
import { assertLegalRunTransition, type RunStatus } from "./statusTransitions.js";
import type { ExtensionProgress } from "./runLimitDecision.js";
import type { Role } from "./types.js";
import { isRunnerMode } from "./runnerModes.js";

/**
 * D#2 H09b, correction C10, pass/fail 13: "Every write of
 * `agent_runs.status` is compare-and-set... A single function makes all
 * of these writes." This file is that function, plus the one INSERT that
 * creates a row (test/importBoundary.test.ts checks: every `UPDATE
 * agent_runs` in `packages/runner/src` lives here, with `status = $…` in
 * its `WHERE`).
 *
 * **H09c (correction C37): no direct SQL on `agent_runs` any more.** The
 * INSERT and the compare-and-set UPDATE go through the SECURITY DEFINER
 * functions `agent_run_create` / `agent_run_set_status` (migration 0642),
 * executable only by the NOLOGIN role `agent_run_writer`, inside the same
 * `withTenant` transaction as the `run_events` / domain-event writes (so
 * they stay atomic). `app_user` cannot write the gate-relevant columns any
 * more, so the pool these functions are handed MUST be a login that is a
 * member of BOTH `app_user` and `agent_run_writer`. Public signatures are
 * unchanged (`pool` first) because `packages/pipeline/src` calls them with
 * a single pool: the composition root (H14c) supplies such a pool. This
 * package reads no connection string from `process.env`; the pool is the
 * caller's dependency, with no default. `test/noDirectAgentRunsWrites.test.ts`
 * fails on any `INSERT INTO`/`UPDATE agent_runs` SQL text under
 * `packages/** /src`.
 *
 * Deep-imports `@fx/core`'s `withTenant` (H09b is its first consumer
 * outside `@fx/core` itself; that package has no `main`/`exports` field
 * yet, the same pattern it already uses for `@fx/db`) rather than
 * re-deriving a third copy.
 */

export interface InsertAgentRunParams {
  /** Pre-generated by the caller (`startAgentRun`) -- `admit`'s
   * `reserve()` needs a `runId` that already exists as an `agent_runs`
   * row (the `spend_reservations.run_id` FK), so the id must be known
   * before this INSERT, not read back from it. */
  id: string;
  accountId: string;
  workItemId?: string | null;
  parentRunId?: string | null;
  role: Role;
  /** `'production'` for every H09b sandbox run; `'runner'` for a run a local runner claims (D#6, taken from the target,
   * C12 A1). `'local'` is H04's owner-only dev runner, never written by this package. */
  runtime: "local" | "production" | "runner";
  /** D#6 R3a: the member who started the run. Written by `agent_run_create` only, which refuses a user who is not a
   * member of the account; no later write can change it (0714). */
  initiatedBy?: string | null;
  /**
   * D#6 R4d-5a (C34 section 0): the Spec version the run is built from, written at insert only (`spec_versions.id`; the definer's foreign key refuses
   * another account's). It is what the done check reads the file scope of (`loadAcceptanceScope`), so a Spec re-published mid-run never changes what
   * the run is held to. Absent: the run pins nothing (every run of a role that has no Spec).
   */
  specVersionId?: string | null;
  /**
   * D#6 R4d-5c (C36): the run whose Spec version a follow-on run inherits, when that is not `parentRunId` (a resumed session's own run).
   * When set (even to null, which means "inherit from nobody"), it is the run read; otherwise `parentRunId` is. The create reads that run's `spec_version_id` under the tenant and writes the same value on the
   * new row; it is never the work item's latest version. An explicit `specVersionId` that differs is refused (`SpecVersionMismatchError`).
   * A pushing role (executor, docs-writer) on a `runner_local` repo whose parent has none is refused (`NoSpecVersionError`). Nothing is
   * written in either case.
   */
  specParentRunId?: string | null;
  /** D#5 E9: the environment the run uses, written at insert only. Both or neither (the definer refuses half a record). */
  envVersionId?: string | null;
  imageDigest?: string | null;
  /** Pass/fail 17 / correction C11: written only here, at INSERT time.
   * Nothing in this package ever UPDATEs it. */
  headSha?: string | null;
  /** PR #85 fix round item 4 (CWE-636/362/672): the `repos.execution_mode`
   * `startAgentRun` already resolved before this INSERT (it must succeed
   * against a registered `ExecutionTarget` first -- see
   * `resolveExecutionTarget`), persisted here so `cancelRun` never needs
   * to re-derive it via a `work_items`/`repos` join that can go stale
   * after the fact. `undefined`/`null` for any row not created through
   * `startAgentRun` (this package's other, direct-`insertAgentRun`
   * callers, e.g. its own [pg] test fixtures) -- `cancelRun` treats that
   * absence as "no persisted identity" and fails closed, never guessing
   * `'sandbox'`. */
  executionMode?: string | null;
  /** The `repos.id` `startAgentRun` resolved `executionMode` against.
   * Deliberately NOT re-derived from `work_items.repo_id` at cancel time
   * -- see 0605_execution_mode.sql's header for why that join can go
   * stale (a deleted repo) or simply be a different repo than dispatch
   * actually used. */
  dispatchRepoId?: string | null;
  /** The PR number `startAgentRun`'s caller supplied (meaningful, and
   * required for `sandboxNameFor`, only for the executor role) --
   * likewise persisted once here rather than re-read from a
   * `work_items.gh_number` that can be edited after dispatch. */
  dispatchPrNumber?: number | null;
  /** D#2 H14c-4 (C41 section 4): claims `key` for this run in the SAME
   * transaction as the row (migration 0646), so one key can never own two
   * runs. When the key is already taken the whole transaction rolls back
   * and `IdempotencyKeyTakenError` is thrown: no run row exists. */
  idempotency?: { key: string; requestHash: string };
  /** D#2 H17c-2b (R-ATOMIC): runs INSIDE the create transaction, right after
   * `agent_run_create`, on the same client, so whatever it writes commits with
   * the run row and the idempotency claim or not at all. A throw rolls the whole
   * create back (no run row, no claim). Absent, the create is exactly what it
   * was before this field existed. */
  inCreateTransaction?: (client: PoolClient, runId: string) => Promise<void>;
  /** D#31 API-6b-2 (R-PERSIST): the run's start prompt, kept as one platform-only `run.input` event in the create transaction so a retry can re-use it. */
  startPrompt?: string;
  /** Platform-only facts about how the run was started (a retry's model and escalation), kept in the `run.input` payload under `meta`. */
  startMeta?: Record<string, unknown>;
}

/** D#6 R4d-5c (C36): an explicit Spec version that is not the one the parent run was built against. Nothing was written. */
export class SpecVersionMismatchError extends Error {
  readonly code = "spec_version_mismatch";
  constructor() {
    super("a follow-on run takes its parent's Spec version; another was named");
    this.name = "SpecVersionMismatchError";
  }
}

/** D#6 R4d-5c (C36): a pushing runner run has no Spec version to inherit, so no file list to hold it to. Nothing was written. */
export class NoSpecVersionError extends Error {
  readonly code = "no_spec_version";
  constructor() {
    super("the parent run has no Spec version to inherit");
    this.name = "NoSpecVersionError";
  }
}

/** The roles whose runner runs push commits and so are held to a Spec's file list at done (the same two as `RUNNER_PUSHING_ROLES` in `@fx/gh-policy`, which this package does not depend on). */
const SPEC_PINNED_RUNNER_ROLES: ReadonlySet<string> = new Set(["executor", "docs-writer"]);

/**
 * D#6 R4d-5c (C36): the Spec version a new run is written with. Without a parent it is the caller's (the new-build pin of R4d-5a).
 * With one, it is the parent's, read here on the create's own client so it is under the tenant and inside the create; the caller
 * never computes it. Throws before anything is written.
 */
async function resolveSpecVersionId(client: PoolClient, p: InsertAgentRunParams): Promise<string | null> {
  const parentId = p.specParentRunId !== undefined ? p.specParentRunId : (p.parentRunId ?? null);
  if (!parentId) return p.specVersionId ?? null;
  const { rows } = await client.query<{ spec_version_id: string | null }>("SELECT spec_version_id FROM agent_runs WHERE id = $1 AND account_id = $2", [parentId, p.accountId]);
  const inherited = rows[0]?.spec_version_id ?? null;
  if (p.specVersionId != null && p.specVersionId !== inherited) throw new SpecVersionMismatchError();
  if (inherited === null && isRunnerMode(p.executionMode) && SPEC_PINNED_RUNNER_ROLES.has(p.role)) throw new NoSpecVersionError();
  return inherited;
}

/** Most prompt bytes `run.input` keeps; a longer prompt keeps only its hash, and a retry of that run is refused. */
export const RUN_INPUT_PROMPT_CAP_BYTES = 48 * 1024;

/** Thrown by `insertAgentRun` when `params.idempotency.key` already belongs
 * to a run of this account. Nothing was written. */
export class IdempotencyKeyTakenError extends Error {
  constructor() {
    super("idempotency key already belongs to a run");
    this.name = "IdempotencyKeyTakenError";
  }
}

export const RUN_EVENTS_SEQ_LOCK_SQL = `SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))`;
export const runEventsSeqLockKey = (runId: string): string => `run_events_seq:${runId}`;

/** Next `run_events.seq` for `runId`, inside the SAME transaction as the
 * event about to use it -- `MAX(seq)+1`, not a sequence object. H09b1's
 * own event volume is one row per insert plus one per transition (real
 * per-message streaming is H09b2's), and every caller writes one run at
 * a time, so a race here isn't exercised by this PR's test surface. */
async function nextRunEventSeq(client: PoolClient, runId: string): Promise<number> {
  // H14c-3-2c: writers for one run now overlap, so seq is computed under a per-run transaction advisory lock.
  // packages/discussions/src/comments.ts takes the SAME key (it may not import this package); a test pins both.
  await client.query(RUN_EVENTS_SEQ_LOCK_SQL, [runEventsSeqLockKey(runId)]);
  const { rows } = await client.query<{ next: string }>(
    `SELECT COALESCE(MAX(seq), 0) + 1 AS next FROM run_events WHERE run_id = $1`,
    [runId],
  );
  return Number(rows[0]!.next);
}

/**
 * D#2 H11 criterion 2 (redaction at source): every `run_events.payload`
 * that this package writes is redacted HERE, before it is ever written to
 * Postgres. There are two insert sites in this file, `insertRunEvent` below and
 * `insertAgentOutputLine` after it, and each must call `redactEventPayload`
 * itself; tests pin both. (The discussions package has its own writer.)
 */
async function insertRunEvent(
  client: PoolClient,
  accountId: string,
  runId: string,
  kind: string,
  payload: Record<string, unknown>,
): Promise<void> {
  const seq = await nextRunEventSeq(client, runId);
  await client.query(`INSERT INTO run_events (account_id, run_id, seq, kind, payload) VALUES ($1, $2, $3, $4, $5)`, [
    accountId,
    runId,
    seq,
    kind,
    JSON.stringify(redactEventPayload(payload)),
  ]);
}

/**
 * D#2 RLR-1: one `agent.output` row keyed by the record-file line it came from, written on the caller's client so
 * it commits or rolls back with the reader's cursor. A line that already has a row is dropped by the unique key
 * (a replayed or zombie write); the redaction chokepoint above still applies.
 */
export async function insertAgentOutputLine(
  client: PoolClient,
  p: { accountId: string; runId: string; sourceLine: number; payload: Record<string, unknown> },
): Promise<void> {
  const seq = await nextRunEventSeq(client, p.runId);
  await client.query(
    `INSERT INTO run_events (account_id, run_id, seq, kind, payload, source_line) VALUES ($1, $2, $3, 'agent.output', $4, $5)
     ON CONFLICT (run_id, source_line) WHERE kind = 'agent.output' AND source_line IS NOT NULL DO NOTHING`,
    [p.accountId, p.runId, seq, JSON.stringify(redactEventPayload(p.payload)), p.sourceLine],
  );
}

/**
 * D#6 R2b-3: one event a local runner sent, written on the caller's client in the caller's tenant transaction. The runner's
 * own sequence number and the digest of what it sent under that number key the row (migration 0754), so a batch sent twice
 * stores each event once. A second event under a number already stored is dropped; if its body differs from the stored one it
 * is also recorded, as a `runner.event_conflict` row that names the number and nothing else. The payload goes through the same
 * redaction chokepoint as every other row here.
 */
export async function insertRunnerEvent(
  client: PoolClient,
  p: { accountId: string; runId: string; runnerSeq: number; bodySha256: string; payload: Record<string, unknown> },
): Promise<"stored" | "duplicate" | "conflict"> {
  const seq = await nextRunEventSeq(client, p.runId);
  const inserted = await client.query(
    `INSERT INTO run_events (account_id, run_id, seq, kind, payload, runner_seq, runner_body_sha256) VALUES ($1, $2, $3, 'runner.event', $4, $5, $6)
     ON CONFLICT (run_id, runner_seq) WHERE runner_seq IS NOT NULL DO NOTHING`,
    [p.accountId, p.runId, seq, JSON.stringify(redactEventPayload(p.payload)), p.runnerSeq, p.bodySha256],
  );
  if (inserted.rowCount === 1) return "stored";
  const { rows } = await client.query<{ runner_body_sha256: string }>("SELECT runner_body_sha256 FROM run_events WHERE run_id = $1 AND runner_seq = $2", [p.runId, p.runnerSeq]);
  if (rows[0]?.runner_body_sha256 === p.bodySha256) return "duplicate";
  await insertRunEvent(client, p.accountId, p.runId, "runner.event_conflict", { runner_seq: p.runnerSeq });
  return "conflict";
}

/** D#2 H14c-5c-2a (X-4): one `limit_extended` row per in-run extension. */
export async function recordLimitExtended(
  pool: Pool,
  p: { accountId: string; runId: string; kind: string; extensionsUsed: number; newLimit: number; progress: ExtensionProgress },
): Promise<void> {
  await withTenant(pool, p.accountId, (client) =>
    insertRunEvent(client, p.accountId, p.runId, "limit_extended", {
      kind: p.kind,
      extensions_used: p.extensionsUsed,
      new_limit: p.newLimit,
      progress: p.progress,
    }),
  );
}

/** D#2 H14c-3-2c: one `agent.output` row. The payload is already bounded by `boundAgentOutput`. */
export async function recordAgentOutput(pool: Pool, p: { accountId: string; runId: string; payload: Record<string, unknown> }): Promise<void> {
  await withTenant(pool, p.accountId, (client) => insertRunEvent(client, p.accountId, p.runId, "agent.output", p.payload));
}

/** D#2 H14c-3-2c: the one `agent.output.capped` row a run's finalize leaves when the per-run cap dropped output. */
export async function recordAgentOutputCapped(
  pool: Pool,
  p: { accountId: string; runId: string; droppedMessages: number; droppedBytes: number },
): Promise<void> {
  await withTenant(pool, p.accountId, (client) =>
    insertRunEvent(client, p.accountId, p.runId, "agent.output.capped", { dropped_messages: p.droppedMessages, dropped_bytes: p.droppedBytes }),
  );
}

/**
 * D#6 R2b: one notice row (`runner.waiting` or `runner.ttl_reminder`) on a run that is waiting for a runner, written on the
 * caller's client so it commits with the caller's "no such notice yet" check. The payload is ids and times only.
 */
export async function recordRunnerNotice(
  client: PoolClient,
  p: { accountId: string; runId: string; kind: "runner.waiting" | "runner.ttl_reminder"; payload: Record<string, unknown> },
): Promise<void> {
  await insertRunEvent(client, p.accountId, p.runId, p.kind, p.payload);
}

/** D#2 PREVIEW-RUNNER-EVENTS: one `run.stage` row. The caller has already limited `stage` to a fixed name. */
export async function recordRunStage(pool: Pool, p: { accountId: string; runId: string; stage: string }): Promise<void> {
  await withTenant(pool, p.accountId, (client) => insertRunEvent(client, p.accountId, p.runId, "run.stage", { stage: p.stage }));
}

/** D#2 PREVIEW-RUNNER-EVENTS: one `agent.activity` row. The caller has already reduced the payload to a kind plus a safe path or term. */
export async function recordAgentActivity(
  pool: Pool,
  p: { accountId: string; runId: string; tool: string; path?: string; pattern?: string; command?: string },
): Promise<void> {
  const payload: Record<string, unknown> = { tool: p.tool };
  if (p.path !== undefined) payload.path = p.path;
  if (p.pattern !== undefined) payload.pattern = p.pattern;
  if (p.command !== undefined) payload.command = p.command;
  await withTenant(pool, p.accountId, (client) => insertRunEvent(client, p.accountId, p.runId, "agent.activity", payload));
}

/** D#2 PREVIEW-RUNNER-EVENTS: the one row a run's finish leaves when the per-run activity cap folded events away. */
export async function recordAgentActivityCapped(pool: Pool, p: { accountId: string; runId: string; dropped: number }): Promise<void> {
  await withTenant(pool, p.accountId, (client) => insertRunEvent(client, p.accountId, p.runId, "agent.activity.capped", { dropped: p.dropped }));
}

/** D#2 H09b2, correction C21 item 2: thrown by `insertAgentRun` when the
 * INSERT violates `0625_agent_runs_one_live_executor_per_pr.sql`'s partial
 * unique index -- a second concurrent executor start for the same
 * (account, repo, PR) while an earlier one is still `pending`/`running`. */
export class DuplicateExecutorRunError extends Error {
  constructor() {
    super("a live executor run already exists for this account, repo and PR");
    this.name = "DuplicateExecutorRunError";
  }
}

/** Thrown by `insertAgentRun` when the item the run belongs to is halted (0750's trigger, SQLSTATE HX409). Nothing was written. */
export class WorkItemHaltedError extends Error {
  constructor() {
    super("the work item is halted");
    this.name = "WorkItemHaltedError";
  }
}

/**
 * Thrown by `insertAgentRun` when the executor sandbox the run would reuse is inside a reaper claim (0761's lock, SQLSTATE FXR01).
 * Nothing was written. It is transient: the claim ends when the delete is marked done (or expires after 10 minutes), and the same
 * start then succeeds on a fresh sandbox. Callers retry it with a backoff; none treats it as a refusal of the work.
 */
export class SandboxReapingError extends Error {
  constructor() {
    super("the executor sandbox is being reaped");
    this.name = "SandboxReapingError";
  }
}

const ONE_LIVE_EXECUTOR_PER_PR_INDEX = "agent_runs_one_live_executor_per_pr";

/** The exposure already frozen for this run's work item (its earliest run
 * that has one), else the parent run's. Read through the caller's tenant
 * transaction, so RLS scopes it to the account; `account_id` is also named. */
async function readFrozenExposure(
  client: PoolClient,
  params: InsertAgentRunParams,
): Promise<{ value: unknown; digest: string } | undefined> {
  const { rows } = await client.query<{ resolved_exposure: unknown; exposure_digest: string }>(
    `SELECT resolved_exposure, exposure_digest FROM agent_runs
      WHERE account_id = $1::uuid
        AND resolved_exposure IS NOT NULL AND exposure_digest IS NOT NULL
        AND (work_item_id = $2::uuid OR id = $3::uuid)
      ORDER BY (work_item_id = $2::uuid) DESC NULLS LAST, created_at, id
      LIMIT 1`,
    [params.accountId, params.workItemId ?? null, params.parentRunId ?? null],
  );
  const row = rows[0];
  return row ? { value: row.resolved_exposure, digest: row.exposure_digest } : undefined;
}

/** Inserts a new `agent_runs` row (`status = 'pending'`) plus one
 * `run_events` row for its creation, both through the same `withTenant`
 * transaction (pass/fail 7 / H09.11). The only `agent_runs` INSERT in
 * this file; every later status change goes through `writeRunStatus`.
 *
 * **Exposure (D#2 H-EXPO, amendment 18488789): resolved ONCE per work item
 * and frozen.** Only a work item's FIRST run resolves. Every later run of it
 * (a `resumeAgentRun` row included), and any run whose `parentRunId` has a
 * frozen exposure, copies that exact `resolved_exposure`/`exposure_digest`
 * instead of resolving again, so a feature flip mid-work-item never reaches
 * a resumed session. A run with neither a work item nor a parent resolves on
 * its own. Race safety: the resolution (its own connection, so no connection
 * is held while waiting) happens first; then, inside the insert transaction,
 * a transaction-scoped advisory lock keyed on the work item serialises
 * concurrent first runs and the frozen row is RE-READ under that lock. The
 * loser of the race discards its own resolution and takes the winner's.
 * Resolution runs server-side from the account's own `account_features`
 * rows (no caller field feeds it); a failure throws before anything is
 * written, so no run row exists without a frozen exposure. */
export async function insertAgentRun(pool: Pool, params: InsertAgentRunParams): Promise<{ id: string }> {
  const id = params.id || randomUUID();
  let exposure: { value: unknown; digest: string } | undefined = undefined;
  if (params.workItemId || params.parentRunId) {
    exposure = await withTenant(pool, params.accountId, (client) => readFrozenExposure(client, params));
  }
  if (!exposure) {
    exposure = await resolveExposure(params.accountId, FEATURE_CATALOGUE, pool);
  }
  const resolved = exposure;
  try {
    await withTenant(pool, params.accountId, async (client) => {
      let frozen = resolved;
      if (params.workItemId) {
        await client.query(`SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))`, [
          `agent_run_exposure:${params.accountId}:${params.workItemId}`,
        ]);
        frozen = (await readFrozenExposure(client, params)) ?? resolved;
      }
      const specVersionId = await resolveSpecVersionId(client, params);
      await client.query(
        `SELECT agent_run_create($1::uuid, $2::uuid, $3::uuid, $4::uuid, $5::text, $6::text, $7::text,
                                $8::text, $9::uuid, $10::bigint, $16::uuid, $11::jsonb, $12::text, $13::uuid, $14::text, $15::text)`,
        [
          id,
          params.accountId,
          params.workItemId ?? null,
          params.parentRunId ?? null,
          params.role,
          params.runtime,
          params.headSha ?? null,
          params.executionMode ?? null,
          params.dispatchRepoId ?? null,
          params.dispatchPrNumber ?? null,
          JSON.stringify(frozen.value),
          frozen.digest,
          params.initiatedBy ?? null,
          params.envVersionId ?? null,
          params.imageDigest ?? null,
          specVersionId,
        ],
      );
      if (params.inCreateTransaction) await params.inCreateTransaction(client, id);
      if (params.idempotency) {
        const claim = await client.query(
          `INSERT INTO agent_run_idempotency_keys (account_id, idempotency_key, run_id, request_hash)
           VALUES ($1, $2, $3, $4) ON CONFLICT (account_id, idempotency_key) DO NOTHING`,
          [params.accountId, params.idempotency.key, id, params.idempotency.requestHash],
        );
        // Rolls back the run row just created: the loser of a race leaves nothing behind.
        if (claim.rowCount === 0) throw new IdempotencyKeyTakenError();
      }
      await insertRunEvent(client, params.accountId, id, "run.created", { role: params.role });
      if (params.startPrompt !== undefined) {
        const prompt_sha256 = createHash("sha256").update(params.startPrompt).digest("hex");
        const keep = Buffer.byteLength(params.startPrompt, "utf8") <= RUN_INPUT_PROMPT_CAP_BYTES;
        await insertRunEvent(client, params.accountId, id, "run.input", { ...(keep ? { prompt: params.startPrompt } : {}), prompt_sha256, ...(params.startMeta ? { meta: params.startMeta } : {}) });
      }
    });
  } catch (err) {
    const pgErr = err as { code?: string; constraint?: string } | undefined;
    if (pgErr?.code === "HX409") throw new WorkItemHaltedError();
    if (pgErr?.code === "FXR01") throw new SandboxReapingError();
    if (pgErr?.code === "23505" && pgErr.constraint === ONE_LIVE_EXECUTOR_PER_PR_INDEX) {
      throw new DuplicateExecutorRunError();
    }
    throw err;
  }
  return { id };
}

/**
 * D#6 R3a (C12 A8): records the signed job on a runner run, through the `agent_run_set_runner_job` definer (0714) and no
 * other path. The definer writes once: only to a `pending` runner run with `runtime = 'runner'` and no job yet.
 * Returns whether this call wrote it; false means the run was not in that state (already has a job, already claimed,
 * cancelled) and nothing changed.
 */
export async function writeRunnerJob(pool: Pool, p: { accountId: string; runId: string; job: Record<string, unknown> }): Promise<boolean> {
  return withTenant(pool, p.accountId, async (client) => {
    const { rows } = await client.query<{ written: boolean }>(
      `SELECT agent_run_set_runner_job($1::uuid, $2::uuid, $3::jsonb) AS written`,
      [p.accountId, p.runId, JSON.stringify(p.job)],
    );
    return rows[0]?.written === true;
  });
}

/** The `run_events` kind that records a continuation's branch head at dispatch (D#6 R2b-3f, C22 section 2). */
export const RUNNER_DISPATCH_BASE_KIND = "runner.dispatch_base";

/**
 * D#6 R2b-3f (C21 section 5.3, C22 section 2): the head of the branch a continuation (a fix round, or the follow-up of one) works
 * on, read from GitHub at THIS run's own dispatch and never copied from the parent's. `done` requires the branch head to differ
 * from it, so a run that adds no commit of its own ends `no_commit`. `headOid` is null when the branch did not exist yet. One
 * row per dispatch; `done` reads the newest.
 */
export async function recordRunnerDispatchBase(pool: Pool, p: { accountId: string; runId: string; headOid: string | null }): Promise<void> {
  if (p.headOid !== null && !/^(?:[0-9a-f]{40}|[0-9a-f]{64})$/.test(p.headOid)) throw new TypeError("recordRunnerDispatchBase: headOid must be a git object id or null");
  await withTenant(pool, p.accountId, (client) => insertRunEvent(client, p.accountId, p.runId, RUNNER_DISPATCH_BASE_KIND, { head_oid: p.headOid }));
}

/**
 * D#6 R2b-3f (C25 section 1.2): the shape of every branch a runner run pushes, and so of every branch a continuation may continue:
 * `fx/<run id>-g<lease generation>`. The generation is a positive integer of at most nine digits. The issuer, `done` and the verdict
 * writer all check this one pattern.
 */
export const RUNNER_RUN_BRANCH = /^fx\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}-g[1-9][0-9]{0,8}$/;

/**
 * The run branch a finished runner run's `done` recorded next to its pull request number (C25 section 1.2), or null when the run has none
 * (it was finished some other way, or it named no pull request). Read from the run's `run.status_changed` event written by `done`; a value
 * that is not a run branch is treated as absent. `client` must be under the run's tenant.
 */
export async function readRecordedRunnerBranch(client: PoolClient, p: { accountId: string; runId: string }): Promise<string | null> {
  const { rows } = await client.query<{ branch: string | null }>(
    `SELECT payload->>'branch' AS branch FROM run_events WHERE account_id = $1 AND run_id = $2 AND kind = 'run.status_changed' AND payload->>'viaRunnerDone' = 'true' ORDER BY seq DESC LIMIT 1`,
    [p.accountId, p.runId],
  );
  const branch = rows[0]?.branch;
  return typeof branch === "string" && RUNNER_RUN_BRANCH.test(branch) ? branch : null;
}

/**
 * The pull request the newest executor run of a work item recorded at `done`, with the run branch recorded next to it (C25 section 1.2):
 * the way the pipeline finds a runner run's pull request, never from the issue's number. Only a run whose `done` verdict was `succeeded`
 * counts: a pull request closed for `scope_violation` (or any other failed verdict) is never the review target, even if it is reopened.
 * Null when no succeeded executor run of the item recorded both, or when what was recorded is not a positive pull request number and a run branch. `client` must be under the run's tenant.
 */
export async function readRecordedRunnerPullRequest(client: PoolClient, p: { accountId: string; workItemId: string }): Promise<{ number: number; branch: string } | null> {
  const { rows } = await client.query<{ branch: string | null; pr: string | null }>(
    `SELECT e.payload->>'branch' AS branch, e.payload->>'prNumber' AS pr
       FROM run_events e JOIN agent_runs r ON r.account_id = e.account_id AND r.id = e.run_id
      WHERE e.account_id = $1 AND r.work_item_id = $2 AND r.role = 'executor' AND e.kind = 'run.status_changed'
        AND e.payload->>'viaRunnerDone' = 'true' AND e.payload->>'to' = 'succeeded' AND e.payload->>'branch' IS NOT NULL AND e.payload->>'prNumber' IS NOT NULL
      ORDER BY e.created_at DESC, e.seq DESC LIMIT 1`,
    [p.accountId, p.workItemId],
  );
  const row = rows[0];
  if (!row || typeof row.branch !== "string" || !RUNNER_RUN_BRANCH.test(row.branch) || typeof row.pr !== "string" || !/^[1-9][0-9]{0,9}$/.test(row.pr)) return null;
  const number = Number(row.pr);
  return Number.isSafeInteger(number) ? { number, branch: row.branch } : null;
}

export interface WriteRunStatusParams {
  accountId: string;
  runId: string;
  from: RunStatus;
  to: RunStatus;
  /** PR #85 fix round item 3 (CWE-772): recorded on the `run.status_changed`
   * event when this transition is a dispatch failure (`to: "failed"`
   * from `dispatchOrCleanup`, startAgentRun.ts). Optional -- omitted, every
   * pre-existing caller's event payload is byte-for-byte unchanged. */
  failureReason?: string;
  /** D#2 H09b2 (C10's revised criteria 2-4): the finished run's result
   * columns, written in the SAME transaction as the CAS write, only when
   * it actually updates a row. `undefined` fields are left NULL -- a
   * `refused_spend`/`timed_out` transition (no result to report) simply
   * omits `result` entirely, matching every pre-H09b2 caller. */
  result?: {
    envelope?: Record<string, unknown> | null;
    tokensIn?: number;
    tokensOut?: number;
    usd?: number;
    /** D#2 H09b2 (C10's revised criterion 5, H09.9): `agent_runs.cc_session_id`,
     * read back by a later `resumeAgentRun` call for the SAME PR (the only
     * resumable role, per `isPersistentRole`). Written here rather than at
     * dispatch time because the session id is only known once the sandbox's
     * FIRST event reports it, and `SandboxTarget` learns it from the
     * terminal `NormalizedEvent` it already collects either way. */
    sessionId?: string;
  };
  /** D#6 R2b-3f: set only by a runner's `done`. The cloud's verdict on the run is stored on the `run.status_changed` event itself, in the same
   * transaction as the status write, so a repeat `done` for the same run and generation can replay it (no column, no migration). `prNumber` is
   * the pull request the verdict is about (null when none exists); `prHttpStatus` is the status GitHub refused the pull request with (a number
   * only: never a GitHub message). */
  runnerDone?: { prNumber: number | null; branch?: string; prHttpStatus?: number; detail?: "renamed" | "unknown_change_type" | "no_file_list" };
  /** D#2 H14c-5b-2a (C48 LIMIT-END): a limit ended this run resumably. Only
   * `running -> timed_out` with `run_time`/`model_calls`/`turns`/`silence`, or
   * `running -> killed_spend` with `per_run_usd`; anything else throws before
   * any query. Written as a `checkpoint` event in the same transaction, only
   * when the status write updated a row. `extensionsUsed` counts the in-run extensions (X-4). */
  checkpoint?: LimitCheckpoint | AgentCheckpoint;
  /** D#2 H14c-3-2c (CARRY-17): one `run.metering` row, same transaction, only when the status write updated a row. */
  metering?: {
    meteredUsd: number | null;
    reportedUsd: number | null;
    flags: string[];
    /** D#221 OM-1: the runner's own count of distinct model responses, from the run guard. Written once, in this same call, to
     * `agent_runs.metered_model_calls` (0744). Absent or null leaves the column NULL ("not recorded"); never shown as 0. */
    modelCalls?: number | null;
  };
}

interface CheckpointBase {
  ccSessionId: string | null;
  meteredUsd: number;
  extensionsUsed: number;
}
type LimitCheckpoint = CheckpointBase & { kind: string; reason?: undefined };
/** D#2 H14c-5c-1 (C48 W-3): the agent said it will not finish. `summary` is untrusted display text; only `running -> timed_out`. */
type AgentCheckpoint = CheckpointBase & { reason: "agent_checkpoint"; summary: string };

/** W-3: at most this many UTF-8 bytes of an agent's checkpoint summary are kept. */
export const MAX_CHECKPOINT_SUMMARY_BYTES = 4096;

/** Strips control and format (bidi, zero-width) characters, then caps at 4 KiB on a character boundary. Never parsed for anything. */
export function sanitizeCheckpointSummary(summary: string): string {
  const bytes = Buffer.from(summary.replace(/[\p{Cc}\p{Cf}]/gu, ""), "utf8");
  if (bytes.length <= MAX_CHECKPOINT_SUMMARY_BYTES) return bytes.toString("utf8");
  let end = MAX_CHECKPOINT_SUMMARY_BYTES;
  while (end > 0 && (bytes[end]! & 0xc0) === 0x80) end--;
  return bytes.subarray(0, end).toString("utf8");
}

const CHECKPOINT_KINDS: Readonly<Record<string, readonly string[]>> = {
  timed_out: ["run_time", "model_calls", "turns", "silence"],
  killed_spend: ["per_run_usd"],
};

export type WriteRunStatusResult =
  | { updated: true }
  /** Zero rows touched: another writer already moved this run past
   * `from`. `currentStatus` is read back in the same transaction -- the
   * caller MUST use this, never assume `to` or retry (pass/fail 13: "the
   * caller re-reads the row and never overwrites it"). `undefined` only
   * if the row doesn't exist (a caller bug). */
  | { updated: false; currentStatus: RunStatus | undefined };

/**
 * THE single compare-and-set writer for `agent_runs.status` (pass/fail
 * 13). Calls `assertLegalRunTransition` first, then one
 * `UPDATE ... WHERE account_id = $ AND id = $ AND status = $from`. A race
 * shows up as `rowCount === 0`, never an error -- this re-reads the row
 * and returns its actual status rather than retrying or overwriting.
 *
 * A successful write also inserts one `run_events` row in the same
 * transaction, only when the UPDATE touched a row (pass/fail 7 /
 * H09.11) -- exactly the shape pass/fail 15 asks for domain events too.
 *
 * **Domain events (D#2 C10 pass/fail 15; D#31 API-4b).** Every successful
 * transition (the `UPDATE` touched a row) emits a `run.status_changed`
 * domain event in the SAME transaction as the status write and the
 * `run.status_changed` `run_events` insert above -- a zero-row UPDATE
 * (another writer already moved this run) writes no event, and a caller
 * that rolls back its own transaction after this returns leaves neither
 * the status change nor the event (`withTenant` rolls the whole callback
 * back on any thrown error). The payload carries ids and status enums
 * only (D#31 resolved disagreement 8) -- never `envelope`, `failureReason`
 * text, or anything else a run's own result might contain. `run.status_
 * changed` is not part of the v1 catalogue a customer can subscribe a
 * webhook endpoint to (packages/webhooks/src/payload.ts's
 * `WEBHOOK_EVENT_TYPES`) -- it exists on the outbox for API-5's future SSE
 * account stream and D#37's own notification-feed follow-up, both read
 * from `domain_events` directly rather than through webhook fan-out.
 */
export async function writeRunStatus(pool: Pool, params: WriteRunStatusParams): Promise<WriteRunStatusResult> {
  checkRunStatusParams(params);
  return withTenant(pool, params.accountId, (client) => writeRunStatusOn(client, params));
}

function checkRunStatusParams(params: WriteRunStatusParams): void {
  assertLegalRunTransition(params.from, params.to);
  const checkpoint = params.checkpoint;
  const allowed =
    checkpoint?.reason === "agent_checkpoint" ? params.to === "timed_out" : CHECKPOINT_KINDS[params.to]?.includes((checkpoint as LimitCheckpoint | undefined)?.kind ?? "");
  if (checkpoint && !(params.from === "running" && allowed)) {
    throw new Error("writeRunStatus: a checkpoint needs running -> timed_out (a time/call/turn/silence limit or the agent's own) or running -> killed_spend (per_run_usd)");
  }
}

/** The `run.status_changed` `run_events` row of one status move, with the failure reason when there is one. */
async function recordRunStatusChanged(client: PoolClient, params: Pick<WriteRunStatusParams, "accountId" | "runId" | "from" | "to" | "failureReason" | "runnerDone">): Promise<void> {
  await insertRunEvent(client, params.accountId, params.runId, "run.status_changed", {
    from: params.from,
    to: params.to,
    ...(params.failureReason ? { failureReason: params.failureReason } : {}),
    ...(params.runnerDone
      ? {
          viaRunnerDone: true,
          prNumber: params.runnerDone.prNumber,
          ...(params.runnerDone.branch === undefined ? {} : { branch: params.runnerDone.branch }),
          ...(params.runnerDone.prHttpStatus === undefined ? {} : { prHttpStatus: params.runnerDone.prHttpStatus }),
          ...(params.runnerDone.detail === undefined ? {} : { detail: params.runnerDone.detail }),
        }
      : {}),
  });
}

async function emitRunStatusDomainEvent(client: PoolClient, params: Pick<WriteRunStatusParams, "accountId" | "runId" | "from" | "to">): Promise<void> {
  await emitDomainEvent(client, {
    type: "run.status_changed",
    accountId: params.accountId,
    subjectId: params.runId,
    payload: {
      runId: params.runId,
      from: params.from,
      to: params.to,
    },
  });
}

/**
 * The events of a status move that was written elsewhere, by a database function that holds its own compare-and-set (the
 * execution-mode switch cancels a repo's queued runner runs in the database, 0759): the `run.status_changed` row and the domain
 * event, from the same code `writeRunStatusOn` uses, in the caller's transaction. It writes nothing to `agent_runs`.
 */
export async function recordRunStatusMove(client: PoolClient, params: Pick<WriteRunStatusParams, "accountId" | "runId" | "from" | "to" | "failureReason">): Promise<void> {
  // The database function checks only that the row was `from`; whether `from -> to` is a legal move is this call's to say, before anything is written.
  assertLegalRunTransition(params.from, params.to);
  await recordRunStatusChanged(client, params);
  await emitRunStatusDomainEvent(client, params);
}

/**
 * The same write on a client the caller already holds, inside the caller's tenant transaction (D#6 R2b-3): a runner's claim,
 * its events and the sweeper move a run's status in the SAME transaction as the lease columns they check, so the two commit or
 * roll back together. Everything `writeRunStatus` says holds; the caller owns the transaction and its tenant context.
 */
export async function writeRunStatusOn(client: PoolClient, params: WriteRunStatusParams): Promise<WriteRunStatusResult> {
  checkRunStatusParams(params);
  const checkpoint = params.checkpoint;
  const result = params.result;
  const { rows: written } = await client.query<{ updated: boolean }>(
    `SELECT agent_run_set_status($1::uuid, $2::uuid, $3::text, $4::text, $5::jsonb,
                                 $6::bigint, $7::bigint, $8::numeric, $9::text, $10::integer) AS updated`,
    [
      params.accountId,
      params.runId,
      params.from,
      params.to,
      result?.envelope !== undefined ? JSON.stringify(result.envelope) : null,
      result?.tokensIn ?? null,
      result?.tokensOut ?? null,
      result?.usd ?? null,
      result?.sessionId ?? null,
      params.metering?.modelCalls ?? null,
    ],
  );
  if (written[0]?.updated === true) {
    await recordRunStatusChanged(client, params);
    if (checkpoint) {
      await insertRunEvent(client, params.accountId, params.runId, "checkpoint", {
        ...(checkpoint.reason === "agent_checkpoint"
          ? { reason: "agent_checkpoint" }
          : { reason: "limit", kind: checkpoint.kind }),
        cc_session_id: checkpoint.ccSessionId,
        ...(checkpoint.reason === "agent_checkpoint" ? { summary: sanitizeCheckpointSummary(checkpoint.summary) } : {}),
        metered_usd: checkpoint.meteredUsd,
        extensions_used: checkpoint.extensionsUsed,
      });
    }
    if (params.metering) {
      await insertRunEvent(client, params.accountId, params.runId, "run.metering", {
        metered_usd: params.metering.meteredUsd,
        reported_usd: params.metering.reportedUsd,
        flags: params.metering.flags,
      });
    }
    await emitRunStatusDomainEvent(client, params);
    return { updated: true };
  }
  const { rows } = await client.query<{ status: RunStatus }>(
    `SELECT status FROM agent_runs WHERE account_id = $1 AND id = $2`,
    [params.accountId, params.runId],
  );
  return { updated: false, currentStatus: rows[0]?.status };
}

/**
 * D#2 H09b2 (C10's revised criterion 2, H09.5): "pauses the tenant's
 * queued runs" on a model-key failure -- every OTHER `pending` run for
 * this account (never the run that just failed; its own transition is a
 * separate `writeRunStatus` call). Each row goes through the same CAS
 * writer above (never a bare UPDATE), so `run.status_changed` events stay
 * the single funnel pass/fail 13/15 already require, and a run some other
 * writer already moved off `pending` in the same instant is silently
 * skipped rather than raising `IllegalRunTransitionError`.
 */
export async function pauseQueuedRuns(pool: Pool, accountId: string, excludeRunId: string): Promise<string[]> {
  const pending = await withTenant(pool, accountId, (client) =>
    // A queued runner run (D#6) does not draw on the tenant's model key and waits for a runner, not for the key: it is not paused.
    client.query<{ id: string }>(`SELECT id FROM agent_runs WHERE account_id = $1 AND status = 'pending' AND runtime <> 'runner' AND id <> $2`, [
      accountId,
      excludeRunId,
    ]),
  );
  const paused: string[] = [];
  for (const row of pending.rows) {
    const write = await writeRunStatus(pool, { accountId, runId: row.id, from: "pending", to: "paused" });
    if (write.updated) paused.push(row.id);
  }
  return paused;
}
