import { NextResponse } from "next/server";
import { applySecurityHeaders } from "../lib/shell/headers";
import { WORKSPACE_INDEX_HTML } from "./_generated/workspace-index";

/**
 * D#37 WS-C2 criterion 1: "apps/web serves the built workspace: `/`
 * returns the filtered `index.html` (`Cache-Control: no-cache`)."
 *
 * `WORKSPACE_INDEX_HTML` is generated by
 * apps/web/scripts/copy-workspace.mjs from apps/workspace's
 * profile-filtered build (profiles/cloud.json), which already ran
 * WS-A1's checks.mjs --import/--ship gates and fails the build if
 * either one fails — this handler trusts that content unconditionally,
 * the same way mode/route.ts trusts its own hardcoded body.
 *
 * `dynamic = "force-static"` matches WS-C1's other anonymous, static
 * contract routes (mode/route.ts, branding/route.ts): the response
 * never varies per request (no session, no query params), so Next can
 * precompute it once. The explicit `Cache-Control: no-cache` below
 * still governs what the BROWSER does with it — unlike `/s/**` (WS-D's
 * content-hashed, immutably-cached static prefix), `/` must always be
 * revalidated so a deploy of a new build is picked up on next load.
 */
export const dynamic = "force-static";

export function GET(): NextResponse {
  const res = new NextResponse(WORKSPACE_INDEX_HTML, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "no-cache",
    },
  });
  return applySecurityHeaders(res);
}
