/*!
 * @fulc/sdk — UMD bundle generated by build-ts.mjs.
 * Source of truth: crates/fulc-shell/src-ts/sdk/.
 *
 * Loads as a classic <script src="…"> (no module support required) and
 * defines window.FULC as a side effect. Equivalent to importing the named
 * surface from the ESM build at sdk/fulc-sdk.js.
 */
(function (root) {
  "use strict";

  // ── types.js ─────────────────────────────────────
  // Public type surface for `@fulc/sdk`.
  //
  // Marketplace app developers consume these types via either:
  //  • `import type { … } from "../sdk/fulc-sdk.js"` (TS authoring path)
  //  • the bundled `assets/sdk/fulc-sdk.d.ts` declaration file shipped alongside
  //    the UMD bundle for plain-JS authors using their own toolchain.
  //
  // Keep these types stable — bumping their shape is a breaking change for every
  // installed marketplace app.

  // ── internal.js ─────────────────────────────────────
  // Internal helpers shared across SDK modules. Not part of the public surface.
  //
  // Most of this file deals with one question: "what app id is this code running
  // as?" The answer feeds into namespacing, proxy URLs, and the entitlement
  // surface, so a single wrong guess cascades through the SDK.
  //
  // Resolution order (first match wins):
  //   1. The id passed to `FULC.register({ id })` — explicit and authoritative.
  //   2. `window.__FULC_BASEAPP_ID__` — set by the marketplace launcher (epic-12
  //      task 04) before injecting the app's entry script.
  //   3. The `data-baseapp-id` attribute on the `<script>` tag that loaded the
  //      SDK — useful for plain-JS apps wired by hand.
  //
  // The id is cached after first resolution; subsequent calls return the same
  // value so the proxy URL doesn't drift mid-session.
  let resolvedAppId = null;
  /** Set by `register()` after the dev hands us an explicit id. */
  function setAppId(id) {
      if (!id || typeof id !== "string") {
          throw new Error("fulcrumaxe-os SDK: app id must be a non-empty string");
      }
      if (resolvedAppId && resolvedAppId !== id) {
          console.warn(`fulcrumaxe-os SDK: app id changed from "${resolvedAppId}" to "${id}". The previous id was already used by namespaced state and proxy URLs — expect inconsistencies.`);
      }
      resolvedAppId = id;
  }
  /**
   * Best-effort app id resolution. Returns `null` if no source has supplied one.
   * Callers should treat `null` as "SDK not yet wired up" and surface a clear
   * error rather than silently falling back to a placeholder.
   */
  function getAppIdOrNull() {
      if (resolvedAppId)
          return resolvedAppId;
      if (typeof window !== "undefined") {
          const fromGlobal = window.__FULC_BASEAPP_ID__;
          if (typeof fromGlobal === "string" && fromGlobal.length > 0) {
              resolvedAppId = fromGlobal;
              return resolvedAppId;
          }
          // The script tag that loaded the SDK may carry `data-baseapp-id="…"`.
          // currentScript is null inside modules, so we sweep all <script> tags
          // looking for one that points at our bundle.
          if (typeof document !== "undefined") {
              const scripts = document.querySelectorAll("script[data-baseapp-id]");
              for (const s of Array.from(scripts)) {
                  const id = s.dataset.baseappId;
                  if (typeof id === "string" && id.length > 0) {
                      resolvedAppId = id;
                      return resolvedAppId;
                  }
              }
          }
      }
      return null;
  }
  /** Throws a clear error when no app id has been resolved yet. */
  function requireAppId(operation) {
      const id = getAppIdOrNull();
      if (!id) {
          throw new Error(`fulcrumaxe-os SDK: ${operation} requires an app id. Call FULC.register({ id: "your.app.id", … }) first, or set window.__FULC_BASEAPP_ID__ before loading the SDK.`);
      }
      return id;
  }
  /** Optional verbose logging — turn on with `window.__FULC_DEV_LOG_SDK__ = true`. */
  function debugLog(msg, ...rest) {
      if (typeof window !== "undefined" && window.__FULC_DEV_LOG_SDK__) {
          console.debug(`[fulc-sdk] ${msg}`, ...rest);
      }
  }

  // ── app.js ─────────────────────────────────────
  // App lifecycle: bridges FULC.register({…}) to the desktop's `FULCApps`
  // registry + window manager. This is the entry point every marketplace app
  // calls at top level.
  
  let isReady = false;
  const readyCallbacks = [];
  function fulcApps() {
      if (typeof window === "undefined")
          return null;
      const apps = window.FULCApps;
      return apps && typeof apps.register === "function" ? apps : null;
  }
  function fulcWM() {
      if (typeof window === "undefined")
          return null;
      return window.FULCWM ?? null;
  }
  /**
   * Register the app with the fulcrumaxe-os desktop. Resolves the app id, wires the
   * lifecycle hooks into `FULCApps.register`, and marks the SDK as ready so
   * `ready()` callbacks fire.
   *
   * Calling `register` twice for the same id is a no-op — the existing
   * registration wins. This matches the desktop's tolerate-double-init
   * behaviour for hot reload.
   */
  function register(options) {
      if (!options || typeof options !== "object") {
          throw new TypeError("FULC.register: options object is required");
      }
      if (!options.title || typeof options.title !== "string") {
          throw new TypeError("FULC.register: `title` is required");
      }
      const id = options.id ??
          getAppIdOrNull() ??
          (() => {
              throw new Error("FULC.register: no app id resolved. Pass `id` explicitly or set window.__FULC_BASEAPP_ID__ before the SDK loads.");
          })();
      setAppId(id);
      const apps = fulcApps();
      if (!apps) {
          // Defer the registration until FULCApps shows up. This happens when the
          // SDK is loaded before the core app-registry module — rare in practice
          // (the launcher always loads core first), but worth tolerating.
          debugLog(`register("${id}") deferred — FULCApps not yet available`);
          queueMicrotask(() => register(options));
          return;
      }
      if (typeof apps.get === "function" && apps.get(id)) {
          debugLog(`register("${id}"): already registered, skipping`);
          markReady();
          return;
      }
      const def = {
          id,
          title: options.title,
          icon: options.icon,
          defaultSize: options.defaultSize,
          minSize: options.minSize,
          onOpen: (contentEl, launchArg) => {
              const ctx = { appId: id, contentEl, launchArg };
              try {
                  const result = options.onOpen?.(ctx);
                  if (result && typeof result.then === "function") {
                      result.catch((err) => {
                          console.error(`fulcrumaxe-os app "${id}" onOpen() rejected:`, err);
                      });
                  }
              }
              catch (err) {
                  console.error(`fulcrumaxe-os app "${id}" onOpen() threw:`, err);
              }
          },
          onClose: options.onClose ? (appId) => options.onClose?.(appId) : undefined,
          onFocus: options.onFocus ? (appId) => options.onFocus?.(appId) : undefined,
          onResize: options.onResize ? () => options.onResize?.(id) : undefined,
          onHide: options.onHide ? () => options.onHide?.(id) : undefined,
          onShow: options.onShow ? () => options.onShow?.(id) : undefined,
          onLaunch: options.onLaunch ? (launchArg) => options.onLaunch?.({ appId: id, launchArg }) : undefined,
      };
      apps.register(id, def);
      debugLog(`register("${id}"): wired with title="${options.title}"`);
      markReady();
  }
  function markReady() {
      if (isReady)
          return;
      isReady = true;
      const cbs = readyCallbacks.splice(0);
      for (const cb of cbs) {
          try {
              cb();
          }
          catch (err) {
              console.error("FULC.ready callback threw:", err);
          }
      }
  }
  /**
   * Run a callback once the app is registered with fulcrumaxe-os. Fires immediately if
   * the app is already registered, otherwise queues until `register()` returns.
   *
   * Use this for setup code that depends on the SDK knowing its app id (e.g.
   * preloading state, opening a WebSocket).
   */
  function ready(cb) {
      if (isReady) {
          queueMicrotask(cb);
      }
      else {
          readyCallbacks.push(cb);
      }
  }
  /**
   * Tear down the app: close any open window and unregister. Call this from
   * the parent extension/host when the app is being uninstalled. Most apps
   * don't need to call this themselves — the desktop drives uninstall.
   */
  function destroy() {
      const id = getAppIdOrNull();
      if (!id)
          return;
      const wm = fulcWM();
      try {
          if (wm?.isOpen?.(id))
              wm.close?.(id);
      }
      catch (err) {
          console.warn(`FULC.destroy: failed to close window for "${id}":`, err);
      }
      const apps = fulcApps();
      try {
          apps?.unregister?.(id);
      }
      catch (err) {
          console.warn(`FULC.destroy: failed to unregister "${id}":`, err);
      }
  }

  // ── backend.js ─────────────────────────────────────
  // Typed wrappers around the baseapp proxy:
  //   • request(method, path, body?)   → /api/baseapp/<id>/<path>
  //   • openWS(path)                   → /api/ws/baseapp/<id>/<path>
  //
  // These match the proxy mounted by `crates/baseapp-runtime/src/proxy.rs` and
  // the runtime host in epic-12 task 08. The proxy injects user/tenant headers
  // server-side, so SDK consumers never touch auth.
  
  /** Structured error thrown by `request()` for non-2xx responses. */
  class FULCBackendError extends Error {
      status;
      body;
      constructor(status, message, body) {
          super(message);
          this.name = "FULCBackendError";
          this.status = status;
          this.body = body;
      }
  }
  function joinPath(base, rest) {
      if (!rest)
          return base;
      if (rest.startsWith("/"))
          return base + rest;
      return base + "/" + rest;
  }
  function isJsonBody(body) {
      if (body === undefined || body === null)
          return false;
      if (typeof FormData !== "undefined" && body instanceof FormData)
          return false;
      if (typeof Blob !== "undefined" && body instanceof Blob)
          return false;
      if (typeof ArrayBuffer !== "undefined" && body instanceof ArrayBuffer)
          return false;
      if (ArrayBuffer.isView(body))
          return false;
      if (typeof body === "string")
          return false;
      return true;
  }
  /**
   * Issue an HTTP request to the running app's backend through the fulcrumaxe-os proxy.
   *
   * The path is automatically prefixed with `/api/baseapp/<this-app-id>/`. The
   * proxy injects `X-FULC-User` / `X-FULC-Tenant` server-side; you don't pass
   * any auth headers from JS.
   *
   * Bodies are JSON-encoded by default. Pass `{ raw: true }` to send `FormData`,
   * `Blob`, or raw bytes verbatim.
   *
   * Throws `FULCBackendError` on non-2xx responses (with parsed JSON body if the
   * server returned `Content-Type: application/json`, otherwise the response
   * text).
   */
  async function request(method, path, body, options = {}) {
      const appId = requireAppId(`backend.request("${method} ${path}")`);
      const url = joinPath(`/api/baseapp/${encodeURIComponent(appId)}`, path);
      const headers = {
          Accept: "application/json",
          ...(options.headers ?? {}),
      };
      let payload;
      if (body !== undefined && body !== null) {
          if (options.raw || !isJsonBody(body)) {
              payload = body;
          }
          else {
              payload = JSON.stringify(body);
              if (!("Content-Type" in headers || "content-type" in headers)) {
                  headers["Content-Type"] = "application/json";
              }
          }
      }
      debugLog(`request ${method} ${url}`);
      let res;
      try {
          res = await fetch(url, {
              method,
              headers,
              body: payload,
              credentials: "same-origin",
              signal: options.signal,
          });
      }
      catch (err) {
          throw new FULCBackendError(0, `network error: ${err.message}`, null);
      }
      const ctype = res.headers.get("content-type") ?? "";
      let parsed = null;
      let text = "";
      if (res.status !== 204) {
          text = await res.text();
          if (text.length > 0 && ctype.includes("application/json")) {
              try {
                  parsed = JSON.parse(text);
              }
              catch {
                  parsed = text;
              }
          }
          else {
              parsed = text;
          }
      }
      if (!res.ok) {
          const message = typeof parsed === "object" && parsed !== null && "error" in parsed
              ? String(parsed.error)
              : typeof parsed === "string" && parsed.length > 0
                  ? parsed
                  : `HTTP ${res.status} ${res.statusText}`;
          throw new FULCBackendError(res.status, message, parsed);
      }
      return parsed;
  }
  function isEnvelope(x) {
      return (typeof x === "object" &&
          x !== null &&
          typeof x.type === "string");
  }
  /**
   * Open a WebSocket against `/api/ws/baseapp/<this-app-id>/<path>`.
   *
   * The default protocol is JSON envelopes `{ type, payload }`:
   *   ws.on("todoUpdated", (payload) => …)
   *   ws.send("subscribe", { topic: "todos" })
   *
   * Lifecycle events: `open`, `close`, `error`. Any incoming text frame that
   * isn't a recognisable envelope surfaces on `"message"` instead.
   */
  function openWS(path) {
      const appId = requireAppId(`backend.openWS("${path}")`);
      const proto = typeof location !== "undefined" && location.protocol === "https:" ? "wss:" : "ws:";
      const host = typeof location !== "undefined" ? location.host : "";
      const url = `${proto}//${host}${joinPath(`/api/ws/baseapp/${encodeURIComponent(appId)}`, path)}`;
      debugLog(`openWS ${url}`);
      const sock = new WebSocket(url);
      const listeners = new Map();
      function emit(event, ...args) {
          const set = listeners.get(event);
          if (!set)
              return;
          for (const fn of Array.from(set)) {
              try {
                  fn(...args);
              }
              catch (err) {
                  console.error(`fulcrumaxe-os WS listener for "${event}" threw:`, err);
              }
          }
      }
      sock.addEventListener("open", () => emit("open"));
      sock.addEventListener("error", (e) => emit("error", e));
      sock.addEventListener("close", (e) => emit("close", { code: e.code, reason: e.reason }));
      sock.addEventListener("message", (e) => {
          emit("message", e);
          if (typeof e.data !== "string")
              return;
          try {
              const parsed = JSON.parse(e.data);
              if (isEnvelope(parsed)) {
                  emit(parsed.type, parsed.payload);
              }
          }
          catch {
              // Non-JSON text frames only surface on `"message"`.
          }
      });
      const handle = {
          on(event, listener) {
              let set = listeners.get(event);
              if (!set) {
                  set = new Set();
                  listeners.set(event, set);
              }
              set.add(listener);
          },
          off(event, listener) {
              listeners.get(event)?.delete(listener);
          },
          send(eventOrRaw, payload) {
              if (sock.readyState !== WebSocket.OPEN) {
                  debugLog(`send dropped — socket not open (state=${sock.readyState})`);
                  return;
              }
              if (typeof eventOrRaw === "string" && payload === undefined) {
                  sock.send(eventOrRaw);
              }
              else if (typeof eventOrRaw === "string") {
                  sock.send(JSON.stringify({ type: eventOrRaw, payload }));
              }
              else {
                  sock.send(eventOrRaw);
              }
          },
          close(code, reason) {
              try {
                  sock.close(code, reason);
              }
              catch {
                  // Already closing — ignore.
              }
          },
          get isOpen() {
              return sock.readyState === WebSocket.OPEN;
          },
      };
      return handle;
  }

  // ── state.js ─────────────────────────────────────
  // Per-app `localStorage` wrapper. Every key is namespaced with
  // `fx:<storage_ns>:app:<id>:` so two apps can't collide on the same
  // key, AND two accounts sharing a browser can't collide on the same
  // app's key (D#37 WS-C2 fix round item 3, W2, CWE-359) -- see
  // sdk/state.js's own header for the full reasoning. This bundle is a
  // plain classic script (index.html's own comment: loaded this way so
  // window.FULC exists synchronously for marketplace apps), so it can't
  // use a static `import` of core/storage-ns.js the way sdk/state.js
  // does -- a dynamic import() reaches the exact same module instance
  // instead (ES modules are singletons per URL; whichever script gets
  // there first, static or dynamic, shares the same in-memory
  // namespace state). Every `state.*` call below is invoked well after
  // page load by app code, never at this script's own parse time, so
  // there's no synchronous-read requirement to preserve here the way
  // there was for apps/activation/activation.js's early notice check.

  let _storageNs = null;
  const _storageNsReady = typeof window !== "undefined"
      ? import("../core/storage-ns.js").then((mod) => { _storageNs = mod; return mod; }).catch(() => null)
      : Promise.resolve(null);
  // Named stateNamespace(), NOT namespace(): this whole file is one
  // shared top-level scope (every "── x.js ──" section below is
  // concatenated flat, not wrapped in its own module/IIFE), and
  // sdk/config.js's own section below ALSO declares a function called
  // `namespace()` for its own, differently-prefixed (fulc:config:<id>:)
  // purpose. Two same-named function declarations in one scope are ONE
  // binding -- the later one (config's) silently wins for every caller,
  // including this section's own get/set/remove/clear/keys closures. A
  // real e2e run (apps/workspace/e2e/signin-desktop.spec.ts's fix-round
  // writer test) caught this live: state.set() was landing under
  // config.js's fulc:config: prefix, un-namespaced, instead of this
  // section's own fx:<ns>:app:<id>: one. Confirmed pre-existing (not
  // introduced by this fix round): the original upstream namespace()
  // here collided with config.js's the same way, just never exercised
  // end-to-end before. `ls`/`readRaw`/`writeRaw`/`listKeys` collide the
  // same way but are functionally IDENTICAL between the two sections,
  // so they're harmless today -- mentioned, not fixed, in this fix
  // round's PR (out of C15c's five-writer scope; a real risk for
  // anyone editing either section's storage helpers independently in
  // the future, since a change to one silently changes the other too).
  /** Returns null (never an un-namespaced key) until a namespace exists. */
  function stateNamespace() {
      if (!_storageNs) return null;
      const ns = _storageNs.getNamespace();
      if (!ns) return null;
      return _storageNs.PREFIX + ns + ":app:" + requireAppId("state.*") + ":";
  }
  function ls() {
      try {
          return typeof localStorage !== "undefined" ? localStorage : null;
      }
      catch {
          // Some sandboxed contexts throw on access. Fall back to in-memory.
          return null;
      }
  }
  const memoryFallback = new Map();
  function readRaw(fullKey) {
      const store = ls();
      if (store)
          return store.getItem(fullKey);
      return memoryFallback.get(fullKey) ?? null;
  }
  function writeRaw(fullKey, value) {
      const store = ls();
      if (store) {
          store.setItem(fullKey, value);
      }
      else {
          memoryFallback.set(fullKey, value);
      }
  }
  function removeRaw(fullKey) {
      const store = ls();
      if (store) {
          store.removeItem(fullKey);
      }
      else {
          memoryFallback.delete(fullKey);
      }
  }
  function listKeys(prefix) {
      const store = ls();
      const out = [];
      if (store) {
          for (let i = 0; i < store.length; i++) {
              const k = store.key(i);
              if (k && k.startsWith(prefix))
                  out.push(k.slice(prefix.length));
          }
      }
      else {
          for (const k of memoryFallback.keys()) {
              if (k.startsWith(prefix))
                  out.push(k.slice(prefix.length));
          }
      }
      return out;
  }
  const state = {
      get(key) {
          const ns = stateNamespace();
          if (ns === null)
              return null;
          const raw = readRaw(ns + key);
          if (raw === null)
              return null;
          try {
              return JSON.parse(raw);
          }
          catch (err) {
              console.warn(`fulcrumaxe-os state.get("${key}"): unparseable JSON, returning null`, err);
              return null;
          }
      },
      set(key, value) {
          const ns = stateNamespace();
          if (ns === null) {
              debugLog(`state.set("${key}") skipped: no namespace yet`);
              return;
          }
          let serialised;
          try {
              serialised = JSON.stringify(value);
          }
          catch (err) {
              throw new Error(`fulcrumaxe-os state.set("${key}"): value not JSON-serialisable: ${err.message}`);
          }
          writeRaw(ns + key, serialised);
          debugLog(`state.set("${key}") = ${serialised.length}b`);
      },
      remove(key) {
          const ns = stateNamespace();
          if (ns === null)
              return;
          removeRaw(ns + key);
      },
      clear() {
          const ns = stateNamespace();
          if (ns === null)
              return;
          for (const key of listKeys(ns)) {
              removeRaw(ns + key);
          }
          debugLog(`state.clear() under ${ns}`);
      },
      keys() {
          const ns = stateNamespace();
          if (ns === null)
              return [];
          return listKeys(ns);
      },
  };

  // ── events.js ─────────────────────────────────────
  // In-app pub/sub bus + cross-context BroadcastChannel for the same app id.
  //
  // `on/off/emit` stay inside the current document. `broadcast()` additionally
  // publishes to a `BroadcastChannel("fulc:app:<id>")` so other fulcrumaxe-os contexts
  // (e.g. a popped-out window or a worker) running the same app receive the
  // event too. The local listeners always fire — broadcast is "in addition to,"
  // not "instead of."
  
  const localListeners = new Map();
  let channel = null;
  let channelAppId = null;
  function ensureChannel() {
      if (typeof BroadcastChannel === "undefined")
          return null;
      const appId = requireAppId("events.broadcast");
      if (channel && channelAppId === appId)
          return channel;
      if (channel) {
          try {
              channel.close();
          }
          catch {
              /* ignore */
          }
      }
      channelAppId = appId;
      channel = new BroadcastChannel("fulc:app:" + appId);
      channel.onmessage = (e) => {
          const data = e.data;
          if (!data || typeof data.type !== "string")
              return;
          fire(data.type, data.payload);
      };
      debugLog(`events: opened BroadcastChannel "fulc:app:${appId}"`);
      return channel;
  }
  function fire(event, payload) {
      const set = localListeners.get(event);
      if (!set)
          return;
      for (const fn of Array.from(set)) {
          try {
              fn(payload);
          }
          catch (err) {
              console.error(`fulcrumaxe-os events listener for "${event}" threw:`, err);
          }
      }
  }
  const events = {
      on(event, listener) {
          let set = localListeners.get(event);
          if (!set) {
              set = new Set();
              localListeners.set(event, set);
          }
          const wrapped = listener;
          set.add(wrapped);
          return () => set.delete(wrapped);
      },
      off(event, listener) {
          localListeners.get(event)?.delete(listener);
      },
      emit(event, payload) {
          fire(event, payload);
      },
      broadcast(event, payload) {
          fire(event, payload);
          const ch = ensureChannel();
          if (ch) {
              try {
                  ch.postMessage({ type: event, payload });
              }
              catch (err) {
                  console.warn(`fulcrumaxe-os events.broadcast("${event}") failed:`, err);
              }
          }
      },
  };

  // ── theme.js ─────────────────────────────────────
  // Theme reading + change subscriptions. Wraps `FULCTheme.current()` /
  // `FULCTheme.onChange()` and the `fulc-theme-change` document event.
  //
  // `current()` snapshots the active experience plus a `tokens` map of resolved
  // CSS custom properties (`--accent`, `--bg`, …). Apps that need a token
  // outside the snapshot can call `snap.token("--surface")` to read it from
  // `:root` directly.
  function fulcTheme() {
      if (typeof window === "undefined")
          return null;
      return window.FULCTheme ?? null;
  }
  function readTokens(experience) {
      // The desktop's theme manager applies tokens to `:root` as CSS custom
      // properties. We snapshot whatever the experience declared (so apps see the
      // intended values regardless of cascade overrides) plus fall back to a
      // computed-style read for anything unspecified.
      const out = {};
      if (experience?.tokens) {
          for (const [k, v] of Object.entries(experience.tokens)) {
              out[k] = String(v);
          }
      }
      return out;
  }
  function snapshotFromExperience(experience) {
      const tokens = readTokens(experience);
      return {
          experience,
          tokens,
          token(name) {
              const lookup = name.startsWith("--") ? name : "--" + name;
              if (lookup in tokens)
                  return tokens[lookup];
              if (typeof getComputedStyle !== "undefined" && typeof document !== "undefined") {
                  return getComputedStyle(document.documentElement).getPropertyValue(lookup).trim();
              }
              return "";
          },
      };
  }
  const theme = {
      current() {
          const t = fulcTheme();
          return snapshotFromExperience(t ? t.current() : null);
      },
      onChange(cb) {
          const handler = (e) => {
              const detail = e.detail;
              const exp = detail?.experience ?? null;
              // Prefer the dispatched tokens (they reflect whatever was applied) and
              // fall back to the experience-declared tokens for older event shapes.
              const tokens = detail?.tokens ?? readTokens(exp);
              cb({
                  experience: exp,
                  tokens,
                  token(name) {
                      const lookup = name.startsWith("--") ? name : "--" + name;
                      if (lookup in tokens)
                          return tokens[lookup];
                      if (typeof getComputedStyle !== "undefined" && typeof document !== "undefined") {
                          return getComputedStyle(document.documentElement).getPropertyValue(lookup).trim();
                      }
                      return "";
                  },
              });
          };
          if (typeof document !== "undefined") {
              document.addEventListener("fulc-theme-change", handler);
          }
          return () => {
              if (typeof document !== "undefined") {
                  document.removeEventListener("fulc-theme-change", handler);
              }
          };
      },
  };

  // ── config.js ─────────────────────────────────────
  // Per-app configuration and preferences storage.
  //
  // Dual-storage strategy: values live in namespaced localStorage (fast,
  // synchronous reads) and are synced to the server (persistent across
  // devices/profiles) on every write.
  //
  // Hot-reload: any call to `set()` or `importConfig()` fires a
  // `"config-changed"` event on the shared `events` bus so the running app
  // can react without a full restart.
  
  
  const CONFIG_KEY_PREFIX = "fulc:config:";
  const CONFIG_CHANGED_EVENT = "config-changed";
  function namespace() {
      return CONFIG_KEY_PREFIX + requireAppId("config.*") + ":";
  }
  function ls() {
      try {
          return typeof localStorage !== "undefined" ? localStorage : null;
      }
      catch {
          return null;
      }
  }
  const memFallback = new Map();
  function readRaw(k) {
      const store = ls();
      if (store)
          return store.getItem(k);
      return memFallback.get(k) ?? null;
  }
  function writeRaw(k, v) {
      const store = ls();
      if (store)
          store.setItem(k, v);
      else
          memFallback.set(k, v);
  }
  function listKeys(prefix) {
      const store = ls();
      const out = [];
      if (store) {
          for (let i = 0; i < store.length; i++) {
              const k = store.key(i);
              if (k && k.startsWith(prefix))
                  out.push(k.slice(prefix.length));
          }
      }
      else {
          for (const k of memFallback.keys()) {
              if (k.startsWith(prefix))
                  out.push(k.slice(prefix.length));
          }
      }
      return out;
  }
  // ---------------------------------------------------------------------------
  // Server sync
  // ---------------------------------------------------------------------------
  async function fetchServerConfig(appId) {
      try {
          const res = await fetch(`/api/apps/${encodeURIComponent(appId)}/config`, {
              credentials: "same-origin",
          });
          if (!res.ok)
              return null;
          const body = await res.json();
          // Handle ApiResponse<{ ... }> envelope
          const data = body["data"];
          return data ?? body;
      }
      catch {
          return null;
      }
  }
  async function pushServerConfig(appId, cfg) {
      try {
          const res = await fetch(`/api/apps/${encodeURIComponent(appId)}/config`, {
              method: "PUT",
              credentials: "same-origin",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify(cfg),
          });
          return res.ok;
      }
      catch {
          return false;
      }
  }
  // ---------------------------------------------------------------------------
  // Storage helpers
  // ---------------------------------------------------------------------------
  function getAllFromStorage() {
      const ns = namespace();
      const result = {};
      for (const key of listKeys(ns)) {
          const raw = readRaw(ns + key);
          if (raw !== null) {
              try {
                  result[key] = JSON.parse(raw);
              }
              catch {
                  result[key] = raw;
              }
          }
      }
      return result;
  }
  // ---------------------------------------------------------------------------
  // Settings-panel helpers
  // ---------------------------------------------------------------------------
  function buildFieldInput(key, field, currentValue) {
      const wrapper = document.createElement("div");
      wrapper.className = "fulc-config-field";
      const label = document.createElement("label");
      label.htmlFor = `fulc-config-${key}`;
      label.textContent = field.label ?? key;
      if (field.description) {
          const desc = document.createElement("span");
          desc.className = "fulc-config-field-desc";
          desc.textContent = ` — ${field.description}`;
          label.appendChild(desc);
      }
      wrapper.appendChild(label);
      let input;
      if (field.type === "select" && field.options) {
          const sel = document.createElement("select");
          sel.id = `fulc-config-${key}`;
          sel.name = key;
          for (const opt of field.options) {
              const o = document.createElement("option");
              o.value = opt;
              o.textContent = opt;
              if (currentValue === opt)
                  o.selected = true;
              sel.appendChild(o);
          }
          input = sel;
      }
      else if (field.type === "boolean") {
          const inp = document.createElement("input");
          inp.type = "checkbox";
          inp.id = `fulc-config-${key}`;
          inp.name = key;
          inp.checked = Boolean(currentValue ?? field.default);
          input = inp;
      }
      else if (field.type === "number") {
          const inp = document.createElement("input");
          inp.type = "number";
          inp.id = `fulc-config-${key}`;
          inp.name = key;
          inp.value = String(currentValue ?? field.default ?? "");
          if (field.min !== undefined)
              inp.min = String(field.min);
          if (field.max !== undefined)
              inp.max = String(field.max);
          input = inp;
      }
      else if (field.type === "color") {
          const inp = document.createElement("input");
          inp.type = "color";
          inp.id = `fulc-config-${key}`;
          inp.name = key;
          inp.value = String(currentValue ?? field.default ?? "#000000");
          input = inp;
      }
      else {
          // "string" and fallback
          const inp = document.createElement("input");
          inp.type = "text";
          inp.id = `fulc-config-${key}`;
          inp.name = key;
          inp.value = String(currentValue ?? field.default ?? "");
          input = inp;
      }
      wrapper.appendChild(input);
      return wrapper;
  }
  function readFieldValue(key, field, form) {
      const el = form.querySelector(`#fulc-config-${key}`);
      if (!el)
          return field.default ?? null;
      if (field.type === "boolean")
          return el.checked;
      if (field.type === "number") {
          const n = parseFloat(el.value);
          return Number.isNaN(n) ? (field.default ?? null) : n;
      }
      return el.value;
  }
  // ---------------------------------------------------------------------------
  // Public API
  // ---------------------------------------------------------------------------
  const config = {
      get(key) {
          const raw = readRaw(namespace() + key);
          if (raw === null)
              return null;
          try {
              return JSON.parse(raw);
          }
          catch {
              return null;
          }
      },
      set(key, value) {
          const ns = namespace();
          writeRaw(ns + key, JSON.stringify(value));
          events.emit(CONFIG_CHANGED_EVENT, { key, value });
          debugLog(`config.set("${key}")`);
          const appId = requireAppId("config.set");
          return pushServerConfig(appId, getAllFromStorage()).then(() => undefined);
      },
      getAll() {
          return getAllFromStorage();
      },
      async loadFromServer() {
          const appId = requireAppId("config.loadFromServer");
          const serverCfg = await fetchServerConfig(appId);
          if (!serverCfg)
              return;
          const ns = namespace();
          for (const [k, v] of Object.entries(serverCfg)) {
              writeRaw(ns + k, JSON.stringify(v));
          }
          debugLog(`config.loadFromServer: ${Object.keys(serverCfg).length} keys`);
      },
      onChange(callback) {
          return events.on(CONFIG_CHANGED_EVENT, ({ key, value }) => callback(key, value));
      },
      exportConfig() {
          return JSON.stringify(getAllFromStorage(), null, 2);
      },
      async importConfig(json) {
          const parsed = JSON.parse(json);
          if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
              throw new Error("fulcrumaxe-os config.importConfig: expected a JSON object");
          }
          const obj = parsed;
          const ns = namespace();
          for (const [k, v] of Object.entries(obj)) {
              writeRaw(ns + k, JSON.stringify(v));
          }
          const appId = requireAppId("config.importConfig");
          await pushServerConfig(appId, obj);
          events.emit(CONFIG_CHANGED_EVENT, { key: "*", value: obj });
      },
      async renderSettingsPanel(container, schema) {
          // Try to fetch schema from the manifest when not supplied by the caller.
          let resolvedSchema = schema;
          if (!resolvedSchema) {
              try {
                  const appId = requireAppId("config.renderSettingsPanel");
                  const res = await fetch(`/api/apps/${encodeURIComponent(appId)}`, {
                      credentials: "same-origin",
                  });
                  if (res.ok) {
                      const body = await res.json();
                      resolvedSchema = body?.data?.manifest?.config_schema;
                  }
              }
              catch {
                  /* schema stays undefined */
              }
          }
          container.replaceChildren();
          container.className = "fulc-config-panel";
          if (!resolvedSchema || Object.keys(resolvedSchema).length === 0) {
              const msg = document.createElement("p");
              msg.className = "fulc-config-empty";
              msg.textContent = "No configuration options available for this app.";
              container.appendChild(msg);
              return;
          }
          const currentCfg = config.getAll();
          const form = document.createElement("form");
          form.className = "fulc-config-form";
          form.addEventListener("submit", (e) => e.preventDefault());
          for (const [key, field] of Object.entries(resolvedSchema)) {
              form.appendChild(buildFieldInput(key, field, currentCfg[key] ?? field.default));
          }
          const actions = document.createElement("div");
          actions.className = "fulc-config-actions";
          const saveBtn = document.createElement("button");
          saveBtn.type = "button";
          saveBtn.textContent = "Save";
          saveBtn.className = "fulc-config-save-btn";
          saveBtn.addEventListener("click", async () => {
              saveBtn.disabled = true;
              saveBtn.textContent = "Saving…";
              try {
                  for (const [key, field] of Object.entries(resolvedSchema)) {
                      await config.set(key, readFieldValue(key, field, form));
                  }
                  saveBtn.textContent = "Saved ✓";
                  setTimeout(() => {
                      saveBtn.textContent = "Save";
                      saveBtn.disabled = false;
                  }, 1500);
              }
              catch {
                  saveBtn.textContent = "Error saving";
                  saveBtn.disabled = false;
              }
          });
          const exportBtn = document.createElement("button");
          exportBtn.type = "button";
          exportBtn.textContent = "Export";
          exportBtn.className = "fulc-config-export-btn";
          exportBtn.addEventListener("click", () => {
              const json = config.exportConfig();
              const blob = new Blob([json], { type: "application/json" });
              const url = URL.createObjectURL(blob);
              const a = document.createElement("a");
              a.href = url;
              const appId = requireAppId("config.export");
              a.download = `${appId}-config.json`;
              a.click();
              URL.revokeObjectURL(url);
          });
          const importBtn = document.createElement("button");
          importBtn.type = "button";
          importBtn.textContent = "Import";
          importBtn.className = "fulc-config-import-btn";
          importBtn.addEventListener("click", () => {
              const picker = document.createElement("input");
              picker.type = "file";
              picker.accept = ".json,application/json";
              picker.addEventListener("change", async () => {
                  const file = picker.files?.[0];
                  if (!file)
                      return;
                  try {
                      const text = await file.text();
                      await config.importConfig(text);
                      // Re-render so input values reflect the imported state.
                      await config.renderSettingsPanel(container, resolvedSchema);
                  }
                  catch (err) {
                      console.error("fulcrumaxe-os config.importConfig failed:", err);
                  }
              });
              picker.click();
          });
          actions.appendChild(saveBtn);
          actions.appendChild(exportBtn);
          actions.appendChild(importBtn);
          form.appendChild(actions);
          container.appendChild(form);
      },
  };

  // ── entitlements.js ─────────────────────────────────────
  // Entitlement gating for marketplace apps.
  //
  // epic-28 task 05 will eventually attach a `FULCEntitlements` global that
  // wraps the user's resolved capability set. Until then, the SDK's `can()`
  // returns `true` unless an explicit deny override is set on
  // `window.__FULC_DENY_CAPS__` — this matches the dev resolver's
  // allow-everything behaviour while letting tests simulate denied gates.
  //
  // `gate(element, cap)` overlays a lock icon, intercepts clicks, and (if the
  // user lacks the cap) opens an upgrade modal. If `FULCModals` exposes an
  // `upgradePrompt` helper later (epic-28 task 09), we delegate to it; for now
  // we render a minimal modal in pure DOM so the gate UX works standalone.
  
  function fulcEntitlements() {
      if (typeof window === "undefined")
          return null;
      return window.FULCEntitlements ?? null;
  }
  function fulcModals() {
      if (typeof window === "undefined")
          return null;
      return window.FULCModals ?? null;
  }
  function decide(capability) {
      if (typeof window !== "undefined") {
          const denied = window.__FULC_DENY_CAPS__;
          if (Array.isArray(denied) && denied.includes(capability)) {
              return { capability, allowed: false, reason: "Denied by tenant policy" };
          }
          const granted = window.__FULC_GRANT_CAPS__;
          if (Array.isArray(granted) && granted.includes(capability)) {
              return { capability, allowed: true };
          }
      }
      const ent = fulcEntitlements();
      if (ent?.check) {
          try {
              return ent.check(capability);
          }
          catch (err) {
              console.warn(`fulcrumaxe-os entitlements.check("${capability}") threw, allowing:`, err);
          }
      }
      if (ent?.can) {
          try {
              return { capability, allowed: !!ent.can(capability) };
          }
          catch (err) {
              console.warn(`fulcrumaxe-os entitlements.can("${capability}") threw, allowing:`, err);
          }
      }
      // Default-open in dev — matches the server's wildcard resolver.
      return { capability, allowed: true, reason: "default-open (no FULCEntitlements global)" };
  }
  const GATE_FLAG = "__fulcGated";
  const GATE_LOCK_CLASS = "fulc-sdk-gate-lock";
  const GATE_LOCKED_CLASS = "fulc-sdk-gate-locked";
  const gates = new WeakMap();
  function ensureLockStyle() {
      if (typeof document === "undefined")
          return;
      if (document.getElementById("fulc-sdk-gate-style"))
          return;
      const style = document.createElement("style");
      style.id = "fulc-sdk-gate-style";
      style.textContent = `
  .${GATE_LOCK_CLASS} {
    position: absolute;
    top: 4px;
    right: 4px;
    width: 14px;
    height: 14px;
    pointer-events: none;
    font-size: 12px;
    line-height: 14px;
    text-align: center;
    color: var(--accent, #0c0);
    opacity: 0.85;
  }
  .${GATE_LOCKED_CLASS} { cursor: not-allowed !important; opacity: 0.65; }
  .fulc-sdk-gate-modal-backdrop {
    position: fixed; inset: 0; background: rgba(0,0,0,0.55);
    z-index: 99999; display: flex; align-items: center; justify-content: center;
  }
  .fulc-sdk-gate-modal {
    background: var(--bg, #111); color: var(--fg, #ddd);
    border: 1px solid var(--accent, #0c0);
    padding: 24px 28px; min-width: 320px; max-width: 480px;
    font-family: var(--font-mono, monospace);
  }
  .fulc-sdk-gate-modal h2 { margin: 0 0 12px; font-size: 16px; color: var(--accent, #0c0); }
  .fulc-sdk-gate-modal p { margin: 0 0 20px; font-size: 13px; line-height: 1.5; }
  .fulc-sdk-gate-modal .fulc-sdk-gate-actions { display: flex; gap: 12px; justify-content: flex-end; }
  .fulc-sdk-gate-modal button {
    background: transparent; color: inherit; border: 1px solid var(--accent, #0c0);
    padding: 6px 14px; cursor: pointer; font-family: inherit; font-size: 12px;
  }
  .fulc-sdk-gate-modal button.fulc-sdk-gate-cta {
    background: var(--accent, #0c0); color: var(--bg, #111);
  }
  `;
      document.head.appendChild(style);
  }
  function showUpgradeModal(capability, opts) {
      // Prefer host integration when available — keeps gate UX consistent with
      // future epic-28 work without coupling to it.
      const modals = fulcModals();
      if (modals?.upgradePrompt) {
          try {
              modals.upgradePrompt({
                  capability,
                  message: opts.upgradeMessage,
                  ctaLabel: opts.ctaLabel,
              });
              return;
          }
          catch (err) {
              console.warn("FULCModals.upgradePrompt failed, falling back:", err);
          }
      }
      if (typeof document === "undefined")
          return;
      ensureLockStyle();
      const backdrop = document.createElement("div");
      backdrop.className = "fulc-sdk-gate-modal-backdrop";
      const modal = document.createElement("div");
      modal.className = "fulc-sdk-gate-modal";
      const heading = document.createElement("h2");
      heading.textContent = "Upgrade required";
      const body = document.createElement("p");
      body.textContent =
          opts.upgradeMessage ??
              `This feature requires the "${capability}" capability. Upgrade your plan or contact your tenant admin to enable it.`;
      const actions = document.createElement("div");
      actions.className = "fulc-sdk-gate-actions";
      const dismiss = document.createElement("button");
      dismiss.type = "button";
      dismiss.textContent = "Dismiss";
      const cta = document.createElement("button");
      cta.type = "button";
      cta.className = "fulc-sdk-gate-cta";
      cta.textContent = opts.ctaLabel ?? "Upgrade";
      modal.append(heading, body, actions);
      actions.append(dismiss, cta);
      backdrop.append(modal);
      document.body.appendChild(backdrop);
      const close = () => backdrop.remove();
      dismiss.addEventListener("click", close);
      cta.addEventListener("click", close);
      backdrop.addEventListener("click", (e) => {
          if (e.target === backdrop)
              close();
      });
  }
  const entitlements = {
      can(capability) {
          return decide(capability).allowed;
      },
      check(capability) {
          return decide(capability);
      },
      gate(element, capability, options = {}) {
          if (!element)
              return;
          if (typeof document === "undefined")
              return;
          ensureLockStyle();
          const previous = gates.get(element);
          if (previous) {
              // Re-applying a gate: tear down the old wrapper before re-wiring so the
              // capability/options can change.
              this.ungate(element);
          }
          const decision = decide(capability);
          const allowed = decision.allowed;
          const computedPos = window.getComputedStyle(element).position;
          const prevPosition = element.style.position;
          if (computedPos === "static") {
              element.style.position = "relative";
          }
          let lockEl;
          if (!allowed && !options.noLockIcon) {
              lockEl = document.createElement("span");
              lockEl.className = GATE_LOCK_CLASS;
              lockEl.textContent = "🔒";
              lockEl.setAttribute("aria-hidden", "true");
              element.appendChild(lockEl);
              element.classList.add(GATE_LOCKED_CLASS);
          }
          const prevTitle = element.title;
          if (!allowed) {
              element.title = decision.reason
                  ? `Locked: ${decision.reason}`
                  : `Locked — requires "${capability}"`;
              element.setAttribute("aria-disabled", "true");
          }
          const clickHandler = (e) => {
              const fresh = decide(capability);
              if (fresh.allowed)
                  return;
              e.preventDefault();
              e.stopImmediatePropagation();
              const modals = fulcModals();
              modals?.toast?.(`Locked: ${capability}`, 1800);
              showUpgradeModal(capability, options);
          };
          element.addEventListener("click", clickHandler, { capture: true });
          const state = {
              capability,
              options,
              clickHandler,
              lockEl,
              prevTitle,
              prevPosition,
          };
          gates.set(element, state);
          element[GATE_FLAG] = true;
          debugLog(`gate("${capability}") on element <${element.tagName.toLowerCase()}>: allowed=${allowed}`);
      },
      ungate(element) {
          const state = gates.get(element);
          if (!state)
              return;
          element.removeEventListener("click", state.clickHandler, { capture: true });
          state.lockEl?.remove();
          element.classList.remove(GATE_LOCKED_CLASS);
          element.removeAttribute("aria-disabled");
          if (state.prevTitle === undefined || state.prevTitle === "") {
              element.removeAttribute("title");
          }
          else {
              element.title = state.prevTitle;
          }
          if (state.prevPosition !== undefined) {
              element.style.position = state.prevPosition;
          }
          gates.delete(element);
          delete element[GATE_FLAG];
      },
  };

  // ── window.js ─────────────────────────────────────
  // Window-manipulation helpers scoped to the current app id. Wraps the
  // desktop's `FULCWM` so apps don't have to repeat their id with every call.
  
  function fulcWM() {
      if (typeof window === "undefined")
          return null;
      return window.FULCWM ?? null;
  }
  function getMyWindowEl(id) {
      const wm = fulcWM();
      const list = wm?.getOpen?.() ?? [];
      for (const w of list) {
          if (w.id === id && w.el instanceof HTMLElement)
              return w.el;
      }
      return null;
  }
  const windowApi = {
      setTitle(title) {
          const id = requireAppId("window.setTitle");
          const wm = fulcWM();
          try {
              wm?.renameWindow?.(id, title);
          }
          catch (err) {
              console.warn(`fulcrumaxe-os window.setTitle("${title}"):`, err);
          }
      },
      resize(size) {
          const id = requireAppId("window.resize");
          if (!size || typeof size.w !== "number" || typeof size.h !== "number") {
              throw new TypeError("fulcrumaxe-os window.resize: size.w and size.h must be numbers");
          }
          // No public WM method for programmatic resize; set the inline style on
          // the window element. The window manager observes content reflows and
          // re-snaps as needed.
          const el = getMyWindowEl(id);
          if (!el) {
              debugLog(`window.resize: no open window for "${id}"`);
              return;
          }
          el.style.width = `${size.w}px`;
          el.style.height = `${size.h}px`;
      },
      close() {
          const id = requireAppId("window.close");
          fulcWM()?.close?.(id);
      },
      focus() {
          const id = requireAppId("window.focus");
          fulcWM()?.focus?.(id);
      },
      isOpen() {
          const id = requireAppId("window.isOpen");
          return !!fulcWM()?.isOpen?.(id);
      },
  };

  // ── continuity.js ─────────────────────────────────────
  // Optional session-continuity hooks. Apps that participate in epic-7 task 16
  // session migration register a save callback (returning a JSON-serialisable
  // payload) and a restore callback (called with that payload on resume).
  //
  // Apps that don't register hooks resume with default state — the SDK never
  // crashes if no hooks were set; `collect()` simply returns null.
  
  const saveCallbacks = new Set();
  const restoreCallbacks = new Set();
  const continuity = {
      onSessionSave(cb) {
          const wrapped = cb;
          saveCallbacks.add(wrapped);
          return () => saveCallbacks.delete(wrapped);
      },
      onSessionRestore(cb) {
          const wrapped = cb;
          restoreCallbacks.add(wrapped);
          return () => restoreCallbacks.delete(wrapped);
      },
      async collect() {
          if (saveCallbacks.size === 0)
              return null;
          // Multiple hooks merge into a single payload object — last-write-wins on
          // duplicate keys. Most apps register one hook; the merge supports a
          // future where library code (e.g. an editor framework) registers its own.
          const merged = {};
          for (const cb of saveCallbacks) {
              try {
                  const value = await cb();
                  if (value && typeof value === "object" && !Array.isArray(value)) {
                      Object.assign(merged, value);
                  }
                  else {
                      // Non-object payloads land under a default key so they're still
                      // recoverable. Apps with non-object state should restructure.
                      merged.value = value;
                  }
              }
              catch (err) {
                  console.error("fulcrumaxe-os continuity.onSessionSave callback threw:", err);
              }
          }
          debugLog(`continuity.collect: merged ${saveCallbacks.size} callback(s)`);
          return {
              version: 1,
              payload: merged,
              capturedAt: Date.now(),
          };
      },
      async apply(state) {
          if (restoreCallbacks.size === 0) {
              debugLog("continuity.apply: no restore callbacks registered, ignoring state");
              return;
          }
          for (const cb of restoreCallbacks) {
              try {
                  await cb(state);
              }
              catch (err) {
                  console.error("fulcrumaxe-os continuity.onSessionRestore callback threw:", err);
              }
          }
          debugLog(`continuity.apply: ran ${restoreCallbacks.size} callback(s)`);
      },
  };
  /** Public re-exports so apps can `import { onSessionSave } from "@fulc/sdk"`. */
  const onSessionSave = continuity.onSessionSave.bind(continuity);
  const onSessionRestore = continuity.onSessionRestore.bind(continuity);

  // ── fulc-sdk.js ─────────────────────────────────────
  // `@fulc/sdk` entry point — re-exports the public API and (when loaded in the
  // browser) assigns the same surface to `window.FULC` so plain-JS marketplace
  // apps can use it via `<script type="module">` without any imports of their
  // own.
  //
  // Two equivalent consumption modes:
  //
  //   • TypeScript / ESM apps:
  //       import { register, backend, state } from "../sdk/fulc-sdk.js";
  //
  //   • Plain JavaScript apps:
  //       <script type="module" src="/sdk/fulc-sdk.js"></script>
  //       <script>FULC.register({ id: "com.example.foo", title: "Foo" });</script>
  //
  //   • Plain JavaScript apps with no module support (UMD bundle):
  //       <script src="/sdk/fulc-sdk.umd.js"></script>
  //       <script>FULC.register({ id: "com.example.foo", title: "Foo" });</script>
  
  
  
  
  
  
  
  
  
  /**
   * SDK version, written in by the build pipeline. Rendered as a string so the
   * SDK can compare against `min_fulc_version` in manifests at install time.
   */
  const VERSION = "0.1.0";
  /** The grouped `FULC` namespace mirrored on `window.FULC`. */
  const FULC = {
      VERSION,
      register,
      ready,
      destroy,
      backend: { request, openWS, FULCBackendError },
      state,
      config,
      events,
      theme,
      entitlements,
      window: windowApi,
      continuity,
      onSessionSave,
      onSessionRestore,
  };
  // `window.FULC` is declared (loosely typed) in `src-ts/types/fulc.d.ts` so a
  // re-declaration here would conflict. External consumers get the typed
  // surface from the published `assets/sdk/fulc-sdk.d.ts` instead, and internal
  // callers should `import type { FULC } from "../sdk/fulc-sdk.js"` when they
  // want full IntelliSense.
  
  FULC;

  if (root) {
    if (root.FULC) {
      console.warn(
        "fulcrumaxe-os SDK (umd): window.FULC already defined; not overwriting."
      );
    } else {
      root.FULC = FULC;
    }
  }
})(typeof window !== "undefined" ? window : null);
